import { GuideShell, GuideSection } from "@/components/GuideShell";

export const metadata = {
  title: "Home EV Charging Guide | Australian Energy Assessments",
  description: "Independent guidance for matching home EV charging to driving, solar, tariffs, electrical capacity and strata requirements.",
};

export default function EvChargingGuidePage() {
  return <GuideShell label="Home EV charging guide" title="Match charging speed to driving and the home's capacity" introduction="A dedicated charger is not automatically necessary. Start with daily driving, parking, charging windows and the existing electrical installation, then decide whether a standard outlet or controlled charger is appropriate.">
    <GuideSection eyebrow="Prepare the evidence" title="Understand the charging job"><div className="guide-principle-grid"><article><strong>Daily driving</strong><p>Record typical kilometres, days at home, arrival time and how often the vehicle needs a rapid turnaround. Average demand can be more useful than maximum battery size.</p></article><article><strong>Parking and cable route</strong><p>Confirm off-street parking, weather exposure, cable management, impact protection and safe access without creating a trip or public-path hazard.</p></article><article><strong>Energy timing</strong><p>Check rooftop solar, controlled tariffs, off-peak windows and whether smart charging can avoid household peaks or follow surplus solar.</p></article></div></GuideSection>
    <GuideSection eyebrow="Choose the approach" title="Use only as much charging power as the household needs"><div className="guide-two-column"><div><h3>Standard power point</h3><p>Australian Government guidance notes that ordinary outlet charging may be enough for modest daily driving. The outlet and charging arrangement still need to be safe, suitable and used without extension leads or power boards.</p><ul><li>Check the vehicle&apos;s supplied charging equipment</li><li>Use a dedicated, suitable outlet where advised</li><li>Confirm the overnight range recovered</li><li>Do not assume an old outlet is suitable</li></ul></div><div><h3>Dedicated smart charger</h3><p>A 7 to 22 kW charger can charge faster, but a licensed electrician must assess supply, phases, switchboard capacity and the vehicle&apos;s actual AC charging limit.</p><ul><li>Check solar-following and schedule controls</li><li>Confirm load management behaviour</li><li>Include network or supply requirements</li><li>Check app support and offline operation</li></ul></div></div></GuideSection>
    <GuideSection eyebrow="Houses and shared buildings" title="Confirm authority before installation"><div className="guide-program"><p>Apartment and strata projects may need owners corporation approval, a shared load-management plan, metering and a fair method for recovering electricity costs. A single resident&apos;s charger should not bypass a whole-building capacity decision.</p><div className="guide-source-links"><a href="https://www.energy.gov.au/electric-vehicles/owning-electric-vehicle/how-charge-your-electric-vehicle" target="_blank" rel="noreferrer">Australian Government charging guidance</a><a href="https://www.energy.gov.au/electric-vehicles/owning-electric-vehicle/charging-options-houses-and-strata-buildings" target="_blank" rel="noreferrer">House and strata charging options</a></div></div></GuideSection>
    <GuideSection eyebrow="Written quote checklist" title="Make capacity, controls and enabling work visible"><ul className="guide-checklist"><li>Exact charger model and rated power</li><li>Vehicle and connector compatibility</li><li>Cable route, mounting and weather protection</li><li>New circuit and switchboard work</li><li>Load management and solar integration</li><li>Metering and user access controls</li><li>Testing, certificates and network requirements</li><li>Product, software and workmanship support</li></ul></GuideSection>
  </GuideShell>;
}
