export const DATABASE_PAGE_SIZES = [25, 50, 100] as const;
export const DATABASE_MAX_OFFSET = 10_000;
export const DATABASE_MAX_BODY_LENGTH = 64_000;
export const DATABASE_MAX_CELL_LENGTH = 4_000;
export const DATABASE_MAX_ROW_LENGTH = 32_000;

const IDENTIFIER_PATTERN = /^[A-Za-z_][A-Za-z0-9_]{0,63}$/;
const SEARCH_TABLES = [
  "tlink_product_search",
  "tlink_account_search",
  "tlink_customer_search",
  "tlink_opportunity_search",
  "tlink_crm_customer_search",
] as const;

const READ_ONLY_TABLES: Record<string, string> = {
  admin_users: "Operations access is managed in Access & audit so owner recovery safeguards remain active.",
  admin_audit_log: "Administrator accountability records are append-only.",
  admin_notifications: "Operations notifications are managed by their source workflows.",
  admin_notification_deliveries: "Notification delivery history is an immutable operational record.",
  lead_rate_limits: "Rate-limit state is maintained by the request boundary.",
  stripe_memberships: "Membership state is reconciled from Stripe.",
  stripe_webhook_events: "Webhook receipts are immutable provider evidence.",
  verification_documents: "Verification document records are managed with their protected object storage workflow.",
  trade_crm_integrations: "Provider connections can contain protected credentials and are managed in Integrations.",
  trade_crm_oauth_states: "OAuth state is security-sensitive and lifecycle managed.",
  trade_crm_quote_links: "Secure quote links are managed by the quote sharing workflow.",
  trade_crm_photo_requests: "Secure photo requests are managed by the photo-proof workflow.",
  trade_crm_payment_links: "Payment requests are reconciled from the connected payment provider.",
  trade_crm_accounting_documents: "Accounting documents are provider-neutral financial records.",
  trade_crm_quick_invoices: "Invoice totals and status are managed by the invoice correction ledger.",
  trade_crm_commercial_handovers: "Accepted commercial handoffs are immutable financial records.",
  trade_purchase_orders: "Purchase orders are authoritative commercial records.",
  trade_purchase_order_items: "Purchase-order lines belong to an authoritative commercial record.",
  trade_membership_credits: "Membership credits are reconciled financial records.",
  certificate_price_sync_runs: "Certificate price sync state is maintained by the scheduled workflow.",
  api_performance_samples: "Performance samples are generated by route monitoring.",
};

const IMMUTABLE_SUFFIXES = [
  "_events",
  "_revisions",
  "_history",
  "_receipts",
  "_acceptances",
  "_snapshots",
  "_signoffs",
  "_credits",
  "_allocations",
  "_acknowledgements",
  "_deliveries",
  "_sync_changes",
  "_runs",
  "_outbox",
] as const;

const GENERATED_TABLES = new Set([
  "trade_crm_counters",
  "trade_data_import_batches",
  "trade_data_import_rows",
  "certificate_price_sync_runs",
  "api_performance_samples",
]);

const MUTABLE_TABLES: Record<string, { canInsert: boolean; canDelete: boolean; reason: string }> = {
  workspace_list_views: {
    canInsert: true,
    canDelete: true,
    reason: "Base owner-scoped view preferences can be inserted, and any selected saved-view row can be deleted. Named views must be created in their product workspace.",
  },
  trade_team_working_hours: {
    canInsert: true,
    canDelete: true,
    reason: "Working-hour availability can be repaired one row at a time.",
  },
  trade_team_unavailability: {
    canInsert: true,
    canDelete: true,
    reason: "Recorded time off can be repaired one row at a time.",
  },
};

const TRADE_VIEW_KEYS = new Set(["supplier-products", "installer-jobs", "installer-customers", "purchasing-orders"]);
const ADMIN_VIEW_KEYS = new Set(["admin-accounts", "admin-customers", "admin-partners", "admin-opportunities", "admin-products"]);

export type DatabaseTablePolicy = {
  visible: boolean;
  canInsert: boolean;
  canDelete: boolean;
  reason: string;
};

export type DatabaseColumn = {
  name: string;
  type: string;
  notNull: boolean;
  defaultValue: string | null;
  primaryKeyPosition: number;
  hidden: number;
  protected: boolean;
};

export type DatabasePresentedRow = {
  values: Record<string, unknown>;
  clippedColumns: string[];
};

export class DatabaseConsoleInputError extends Error {
  readonly status: number;
  readonly publicMessage: string;

  constructor(publicMessage: string, status = 400) {
    super(publicMessage);
    this.name = "DatabaseConsoleInputError";
    this.status = status;
    this.publicMessage = publicMessage;
  }
}

export function quoteDatabaseIdentifier(value: string) {
  if (!IDENTIFIER_PATTERN.test(value)) {
    throw new DatabaseConsoleInputError("The selected database identifier is not valid.");
  }
  return `"${value}"`;
}

function isSearchShadowTable(name: string) {
  return SEARCH_TABLES.some((searchTable) => name.startsWith(`${searchTable}_`));
}

export function databaseTablePolicy(name: string, sql = ""): DatabaseTablePolicy {
  if (!IDENTIFIER_PATTERN.test(name) || name === "d1_migrations" || name.startsWith("sqlite_") || name.startsWith("_cf_") || name.startsWith("__") || name.endsWith("_migrations") || isSearchShadowTable(name)) {
    return { visible: false, canInsert: false, canDelete: false, reason: "Internal SQLite or Sites storage is not exposed." };
  }
  if (READ_ONLY_TABLES[name]) return { visible: true, canInsert: false, canDelete: false, reason: READ_ONLY_TABLES[name] };
  if (SEARCH_TABLES.includes(name as (typeof SEARCH_TABLES)[number]) || /CREATE\s+VIRTUAL\s+TABLE/i.test(sql)) {
    return { visible: false, canInsert: false, canDelete: false, reason: "Search indexes are maintained automatically from their source tables." };
  }
  if (GENERATED_TABLES.has(name)) {
    return { visible: true, canInsert: false, canDelete: false, reason: "This table is generated by an application workflow." };
  }
  if (IMMUTABLE_SUFFIXES.some((suffix) => name.endsWith(suffix))) {
    return { visible: true, canInsert: false, canDelete: false, reason: "Event, revision, delivery and ledger records are append-only." };
  }
  if (MUTABLE_TABLES[name]) return { visible: true, ...MUTABLE_TABLES[name] };
  return {
    visible: true,
    canInsert: false,
    canDelete: false,
    reason: "This table is browse-only because its normal workflow owns related records and side effects.",
  };
}

export function isProtectedDatabaseColumn(name: string) {
  const normalised = name.toLowerCase();
  return /(^|_)(password|secret|credential|api_key|access_token|refresh_token|client_secret)(_|$)/.test(normalised)
    || /(^|_)(token|hash|encrypted)(_|$)/.test(normalised)
    || normalised === "object_key" || normalised === "push_token";
}

export function normaliseDatabaseColumn(row: Record<string, unknown>): DatabaseColumn {
  const name = String(row.name || "");
  quoteDatabaseIdentifier(name);
  return {
    name,
    type: String(row.type || "").trim().toUpperCase(),
    notNull: Number(row.notnull || 0) === 1,
    defaultValue: row.dflt_value === null || row.dflt_value === undefined ? null : String(row.dflt_value),
    primaryKeyPosition: Number(row.pk || 0),
    hidden: Number(row.hidden || 0),
    protected: isProtectedDatabaseColumn(name),
  };
}

export function databasePageSize(value: string | null) {
  const parsed = Number(value);
  return DATABASE_PAGE_SIZES.includes(parsed as (typeof DATABASE_PAGE_SIZES)[number]) ? parsed : 25;
}

export function databaseOffset(value: string | null) {
  const parsed = Number(value);
  return Number.isInteger(parsed) && parsed >= 0 && parsed <= DATABASE_MAX_OFFSET ? parsed : 0;
}

export function sqliteAffinity(type: string): "integer" | "text" | "blob" | "real" | "numeric" {
  const declared = type.toUpperCase();
  if (declared.includes("INT")) return "integer";
  if (declared.includes("CHAR") || declared.includes("CLOB") || declared.includes("TEXT")) return "text";
  if (!declared || declared.includes("BLOB")) return "blob";
  if (declared.includes("REAL") || declared.includes("FLOA") || declared.includes("DOUB")) return "real";
  return "numeric";
}

function binaryByteLength(value: unknown) {
  if (value instanceof ArrayBuffer) return value.byteLength;
  if (ArrayBuffer.isView(value)) return value.byteLength;
  if (Array.isArray(value) && value.every((item) => Number.isInteger(item) && item >= 0 && item <= 255)) return value.length;
  return null;
}

export function presentDatabaseRow(row: Record<string, unknown>, columns: DatabaseColumn[]): DatabasePresentedRow {
  const values: Record<string, unknown> = {};
  const clippedColumns: string[] = [];
  let remainingLength = DATABASE_MAX_ROW_LENGTH;
  for (const column of columns.filter((item) => item.hidden === 0)) {
    const value = row[column.name];
    if (column.protected && value !== null && value !== undefined && value !== "") {
      values[column.name] = "[protected]";
      continue;
    }
    const binaryLength = binaryByteLength(value);
    if (binaryLength !== null) {
      const size = binaryLength;
      values[column.name] = `[BLOB ${size} bytes]`;
      continue;
    }
    if (typeof value === "string") {
      const availableLength = Math.max(0, Math.min(DATABASE_MAX_CELL_LENGTH, remainingLength));
      if (value.length > availableLength) {
        values[column.name] = availableLength ? `${value.slice(0, availableLength)}...` : "[clipped]";
        clippedColumns.push(column.name);
      } else {
        values[column.name] = value;
      }
      remainingLength -= Math.min(value.length, availableLength);
      continue;
    }
    if (typeof value === "object" && value !== null) {
      values[column.name] = "[unsupported value]";
      clippedColumns.push(column.name);
      continue;
    }
    values[column.name] = value ?? null;
  }
  return { values, clippedColumns };
}

function numericValue(value: unknown, column: DatabaseColumn, integer: boolean) {
  const parsed = typeof value === "number" ? value : typeof value === "string" && value.trim() ? Number(value) : Number.NaN;
  if (!Number.isFinite(parsed) || (integer && !Number.isSafeInteger(parsed))) {
    throw new DatabaseConsoleInputError(`${column.name} must be ${integer ? "a whole number" : "a finite number"}.`);
  }
  return parsed;
}

export function databaseBindingValue(column: DatabaseColumn, value: unknown) {
  if (value === null) {
    if (column.notNull) throw new DatabaseConsoleInputError(`${column.name} cannot be null.`);
    return null;
  }
  if (typeof value === "object" || value === undefined) {
    throw new DatabaseConsoleInputError(`${column.name} has an unsupported value.`);
  }
  const affinity = sqliteAffinity(column.type);
  if (affinity === "blob") throw new DatabaseConsoleInputError(`${column.name} is a BLOB column and cannot be entered in this console.`);
  if (affinity === "integer" && typeof value === "boolean") return value ? 1 : 0;
  if (affinity === "integer") return numericValue(value, column, true);
  if (affinity === "real" || affinity === "numeric") return numericValue(value, column, false);
  if (typeof value !== "string") throw new DatabaseConsoleInputError(`${column.name} must be text.`);
  if (value.length > DATABASE_MAX_CELL_LENGTH) throw new DatabaseConsoleInputError(`${column.name} is longer than ${DATABASE_MAX_CELL_LENGTH} characters.`);
  return value;
}

function isAutoIntegerPrimaryKey(column: DatabaseColumn, primaryKeyColumns: DatabaseColumn[]) {
  return primaryKeyColumns.length === 1 && column.primaryKeyPosition === 1 && sqliteAffinity(column.type) === "integer";
}

function asValueRecord(value: unknown, message: string): Record<string, unknown> {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new DatabaseConsoleInputError(message);
  return value as Record<string, unknown>;
}

export function prepareDatabaseInsert(columns: DatabaseColumn[], input: unknown) {
  const values = { ...asValueRecord(input, "Enter the row values to add.") };
  if (JSON.stringify(values).length > DATABASE_MAX_BODY_LENGTH) throw new DatabaseConsoleInputError("The row is too large for this console.", 413);
  const available = columns.filter((column) => column.hidden === 0);
  const byName = new Map(available.map((column) => [column.name, column]));
  const primaryKeyColumns = available.filter((column) => column.primaryKeyPosition > 0);
  const now = new Date().toISOString();
  const idColumn = byName.get("id");
  if (idColumn && primaryKeyColumns.length === 1 && idColumn.primaryKeyPosition === 1 && sqliteAffinity(idColumn.type) === "text") {
    values.id = crypto.randomUUID();
  }
  for (const timestampName of ["created_at", "updated_at"]) {
    const column = byName.get(timestampName);
    if (column?.notNull && column.defaultValue === null && sqliteAffinity(column.type) === "text") values[timestampName] = now;
  }
  const names = Object.keys(values);
  if (names.length > 100) throw new DatabaseConsoleInputError("A row cannot include more than 100 columns.");
  if (names.length > available.length) throw new DatabaseConsoleInputError("The row includes unsupported columns.");
  for (const name of names) if (!byName.has(name)) throw new DatabaseConsoleInputError(`${name} is not a column in this table.`);
  for (const column of available) {
    if (!(column.name in values) && column.notNull && column.defaultValue === null && !isAutoIntegerPrimaryKey(column, primaryKeyColumns)) {
      throw new DatabaseConsoleInputError(`${column.name} is required and has no database default.`);
    }
  }
  const bindings = names.map((name) => databaseBindingValue(byName.get(name)!, values[name]));
  return { names, bindings, values: Object.fromEntries(names.map((name, index) => [name, bindings[index]])) };
}

function requiredText(values: Record<string, unknown>, name: string, maximum = 180) {
  const value = values[name];
  if (typeof value !== "string" || !value.trim() || value.length > maximum) {
    throw new DatabaseConsoleInputError(`${name} must be non-empty text no longer than ${maximum} characters.`);
  }
  return value;
}

export function validateDatabaseInsertForTable(table: string, values: Record<string, unknown>) {
  if (table === "workspace_list_views") {
    requiredText(values, "owner_uid");
    const ownerScope = requiredText(values, "owner_scope", 240);
    const viewKey = requiredText(values, "view_key", 100);
    if (ownerScope.includes(":named:")) throw new DatabaseConsoleInputError("Create named views in their product workspace so names, limits and preferences stay valid.");
    const base = ownerScope === "admin" ? "admin" : ownerScope === "trade" ? "trade" : "";
    const scopedView = viewKey;
    const supported = base === "admin" ? ADMIN_VIEW_KEYS : base === "trade" ? TRADE_VIEW_KEYS : null;
    if (!supported?.has(scopedView)) throw new DatabaseConsoleInputError("owner_scope and view_key must identify a supported admin or trade list view.");
    const preferences = values.preferences === undefined ? "{}" : requiredText(values, "preferences", DATABASE_MAX_CELL_LENGTH);
    try {
      const parsed = JSON.parse(preferences) as unknown;
      if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error("object required");
    } catch {
      throw new DatabaseConsoleInputError("preferences must be a JSON object.");
    }
    return;
  }
  if (table === "trade_team_working_hours") {
    requiredText(values, "owner_uid");
    requiredText(values, "team_member_id");
    const weekday = Number(values.weekday);
    const startMinute = Number(values.start_minute);
    const endMinute = Number(values.end_minute);
    const available = Number(values.is_available ?? 1);
    if (!Number.isInteger(weekday) || weekday < 0 || weekday > 6) throw new DatabaseConsoleInputError("weekday must be a whole number from 0 to 6.");
    if (!Number.isInteger(startMinute) || !Number.isInteger(endMinute) || startMinute < 0 || endMinute > 1440 || startMinute >= endMinute) {
      throw new DatabaseConsoleInputError("Working hours must use valid minutes from midnight, with start_minute before end_minute.");
    }
    if (![0, 1].includes(available)) throw new DatabaseConsoleInputError("is_available must be 0 or 1.");
    return;
  }
  if (table === "trade_team_unavailability") {
    requiredText(values, "owner_uid");
    requiredText(values, "team_member_id");
    requiredText(values, "created_by_uid");
    const startsAt = Date.parse(requiredText(values, "starts_at", 60));
    const endsAt = Date.parse(requiredText(values, "ends_at", 60));
    if (!Number.isFinite(startsAt) || !Number.isFinite(endsAt) || startsAt >= endsAt) {
      throw new DatabaseConsoleInputError("starts_at and ends_at must be valid dates, with starts_at before ends_at.");
    }
  }
}

export function prepareDatabaseKey(columns: DatabaseColumn[], input: unknown) {
  const key = asValueRecord(input, "Enter the complete primary key for the row.");
  const primaryKeyColumns = columns
    .filter((column) => column.hidden === 0 && column.primaryKeyPosition > 0)
    .sort((left, right) => left.primaryKeyPosition - right.primaryKeyPosition);
  if (!primaryKeyColumns.length) throw new DatabaseConsoleInputError("This table has no primary key, so rows cannot be deleted here.", 409);
  if (primaryKeyColumns.length > 90) throw new DatabaseConsoleInputError("This primary key is too wide for a bounded console delete.", 409);
  const names = Object.keys(key).sort();
  const expected = primaryKeyColumns.map((column) => column.name).sort();
  if (names.length !== expected.length || names.some((name, index) => name !== expected[index])) {
    throw new DatabaseConsoleInputError("The complete primary key is required to delete one row.");
  }
  return {
    columns: primaryKeyColumns,
    bindings: primaryKeyColumns.map((column) => databaseBindingValue(column, key[column.name])),
  };
}

export function databaseRowKeyToken(table: string, keyColumns: string[], keyValues: unknown[]) {
  quoteDatabaseIdentifier(table);
  if (!keyColumns.length || keyColumns.length !== keyValues.length) throw new DatabaseConsoleInputError("The complete primary key is required.");
  for (const name of keyColumns) quoteDatabaseIdentifier(name);
  const canonical = JSON.stringify([table, keyColumns.map((name, index) => [name, keyValues[index]])]);
  let hash = 2_166_136_261;
  for (let index = 0; index < canonical.length; index += 1) hash = Math.imul(hash ^ canonical.charCodeAt(index), 16_777_619) >>> 0;
  return hash.toString(16).padStart(8, "0");
}

export function databaseDeleteConfirmation(table: string, keyColumns: string[], keyValues: unknown[]) {
  return `DELETE ${table} ${databaseRowKeyToken(table, keyColumns, keyValues)}`;
}

function databaseAuditStatement(
  db: D1Database,
  adminUid: string,
  action: "database.row_insert" | "database.row_delete",
  table: string,
  entityId: string,
  metadata: Record<string, unknown>,
  existsPredicate = "",
  existsBindings: unknown[] = [],
) {
  const identifier = quoteDatabaseIdentifier(table);
  const summary = action === "database.row_insert" ? `Added one row to ${table}.` : `Deleted one row from ${table}.`;
  const condition = existsPredicate ? `WHERE EXISTS (SELECT 1 FROM ${identifier} WHERE ${existsPredicate})` : "";
  return db.prepare(`
    INSERT INTO admin_audit_log (id, admin_uid, action, entity_type, entity_id, summary, metadata, created_at)
    SELECT ?, ?, ?, 'database_row', ?, ?, ?, ? ${condition}
  `).bind(
    crypto.randomUUID(),
    adminUid,
    action,
    entityId,
    summary,
    JSON.stringify(metadata).slice(0, 4_000),
    new Date().toISOString(),
    ...existsBindings,
  );
}

export function databaseInsertStatements(
  db: D1Database,
  adminUid: string,
  table: string,
  columns: DatabaseColumn[],
  prepared: ReturnType<typeof prepareDatabaseInsert>,
) {
  const identifier = quoteDatabaseIdentifier(table);
  const columnSql = prepared.names.map(quoteDatabaseIdentifier).join(", ");
  const placeholders = prepared.names.map(() => "?").join(", ");
  const insert = prepared.names.length
    ? db.prepare(`INSERT INTO ${identifier} (${columnSql}) VALUES (${placeholders})`).bind(...prepared.bindings)
    : db.prepare(`INSERT INTO ${identifier} DEFAULT VALUES`);
  const keyColumns = columns
    .filter((column) => column.hidden === 0 && column.primaryKeyPosition > 0)
    .sort((left, right) => left.primaryKeyPosition - right.primaryKeyPosition);
  const hasCompleteKey = keyColumns.length > 0 && keyColumns.every((column) => Object.hasOwn(prepared.values, column.name));
  const keyValues = hasCompleteKey ? keyColumns.map((column) => prepared.values[column.name]) : [];
  const entityId = hasCompleteKey
    ? `${table}:${databaseRowKeyToken(table, keyColumns.map((column) => column.name), keyValues)}`
    : table;
  return [
    insert,
    databaseAuditStatement(db, adminUid, "database.row_insert", table, entityId, {
      table,
      primaryKeyColumns: keyColumns.map((column) => column.name),
      changedColumns: prepared.names,
    }),
  ];
}

export function databaseDeleteStatements(
  db: D1Database,
  adminUid: string,
  table: string,
  keyColumns: string[],
  keyValues: unknown[],
) {
  const identifier = quoteDatabaseIdentifier(table);
  const predicate = keyColumns.map((name) => `${quoteDatabaseIdentifier(name)} = ?`).join(" AND ");
  const keyToken = databaseRowKeyToken(table, keyColumns, keyValues);
  return [
    databaseAuditStatement(
      db,
      adminUid,
      "database.row_delete",
      table,
      `${table}:${keyToken}`,
      { table, primaryKeyColumns: keyColumns },
      predicate,
      keyValues,
    ),
    db.prepare(`DELETE FROM ${identifier} WHERE ${predicate}`).bind(...keyValues),
  ];
}

export function databaseConsoleErrorResponse(error: unknown) {
  if (error instanceof DatabaseConsoleInputError) {
    return { status: error.status, message: error.publicMessage };
  }
  const detail = error instanceof Error ? error.message : String(error || "");
  if (/FOREIGN KEY constraint failed/i.test(detail)) {
    return { status: 409, message: "This row is still referenced by other records. Remove those links through their normal workflow first." };
  }
  if (/UNIQUE constraint failed/i.test(detail)) {
    return { status: 409, message: "That row conflicts with an existing unique value." };
  }
  if (/NOT NULL constraint failed|CHECK constraint failed|datatype mismatch/i.test(detail)) {
    return { status: 400, message: "The row does not satisfy this table's database rules." };
  }
  return null;
}
