export const CERTIFICATE_CODES = ["STC", "ESC", "VEEC", "PRC", "LGC", "ACCU", "SMC"] as const;

export type CertificateCode = (typeof CERTIFICATE_CODES)[number];

export interface CertificateDefinition {
  code: CertificateCode;
  name: string;
  region: string;
  relevance: "Household upgrades" | "Broader energy market";
  plainEnglish: string;
  represents: string;
  whyPriceMatters: string;
  officialUrl: string;
  colour: string;
}

export interface CertificateTrade {
  code: CertificateCode;
  tradedOn: string;
  priceCents: number;
}

export interface CertificatePricePoint {
  tradedOn: string;
  priceCents: number;
}

export interface CertificatePriceSeries extends CertificateDefinition {
  latest: CertificatePricePoint | null;
  points: CertificatePricePoint[];
}

export interface CertificatePriceDataset {
  asOf: string;
  source: {
    name: string;
    url: string;
    lastCheckedAt: string;
    status: "current" | "stale";
    note: string;
  };
  certificates: CertificatePriceSeries[];
}

export const CERTIFICATE_DEFINITIONS: CertificateDefinition[] = [
  {
    code: "STC",
    name: "Small-scale Technology Certificate",
    region: "Australia-wide",
    relevance: "Household upgrades",
    plainEnglish: "Supports eligible small-scale renewable systems, including rooftop solar, solar water heaters, small wind or hydro systems and eligible solar-connected batteries.",
    represents: "A tradeable unit under the federal Small-scale Renewable Energy Scheme. Most small generation certificates represent one megawatt hour, while eligible batteries use separate legislated factors.",
    whyPriceMatters: "The certificate value can affect the upfront discount shown for an eligible solar or battery installation. The final discount also depends on how many STCs the system can create and the provider's fees.",
    officialUrl: "https://cer.gov.au/glossary",
    colour: "#25f4d2",
  },
  {
    code: "ESC",
    name: "Energy Savings Certificate",
    region: "New South Wales",
    relevance: "Household upgrades",
    plainEnglish: "Rewards eligible activities that reduce energy use in NSW homes and businesses, such as qualifying efficient appliance or equipment upgrades.",
    represents: "One notional megawatt hour of energy saved under the NSW Energy Savings Scheme.",
    whyPriceMatters: "An accredited provider may use the value of created ESCs to help fund an eligible upgrade. The customer offer will not necessarily equal the full spot price.",
    officialUrl: "https://www.energysustainabilityschemes.nsw.gov.au/energy-savings-certificates",
    colour: "#ffd84d",
  },
  {
    code: "VEEC",
    name: "Victorian Energy Efficiency Certificate",
    region: "Victoria",
    relevance: "Household upgrades",
    plainEnglish: "Supports approved energy-saving products and services delivered through the Victorian Energy Upgrades program.",
    represents: "One tonne of carbon dioxide equivalent greenhouse gas emissions avoided by a prescribed Victorian Energy Upgrades activity.",
    whyPriceMatters: "Accredited providers can sell VEECs created by eligible upgrades, which can help fund the discount offered to a household or business.",
    officialUrl: "https://www.esc.vic.gov.au/victorian-energy-upgrades/how-we-regulate-veu-program",
    colour: "#ff8f70",
  },
  {
    code: "PRC",
    name: "Peak Reduction Certificate",
    region: "New South Wales",
    relevance: "Household upgrades",
    plainEnglish: "Rewards eligible activities that make electricity demand lower during the NSW summer peak period.",
    represents: "0.1 kilowatts of peak demand reduction capacity averaged over one hour during the defined summer peak period.",
    whyPriceMatters: "The value can influence the incentive an accredited provider offers for eligible equipment or controls that reduce peak demand.",
    officialUrl: "https://www.energysustainabilityschemes.nsw.gov.au/peak-reduction-certificates",
    colour: "#a78bfa",
  },
  {
    code: "LGC",
    name: "Large-scale Generation Certificate",
    region: "Australia-wide",
    relevance: "Broader energy market",
    plainEnglish: "Supports electricity generated by eligible large renewable power stations such as wind and solar farms.",
    represents: "One megawatt hour of eligible renewable electricity generated or displaced by a large-scale power station.",
    whyPriceMatters: "LGCs mainly affect renewable generation and retailer or business obligations. They are useful market context but are not normally a direct household rebate.",
    officialUrl: "https://cer.gov.au/schemes/renewable-energy-target/large-scale-renewable-energy-target/large-scale-generation-certificates",
    colour: "#60a5fa",
  },
  {
    code: "ACCU",
    name: "Australian Carbon Credit Unit",
    region: "Australia-wide",
    relevance: "Broader energy market",
    plainEnglish: "Rewards eligible projects that avoid greenhouse emissions or remove and store carbon, including land, waste and energy projects.",
    represents: "One tonne of carbon dioxide equivalent emissions avoided or stored by an eligible project.",
    whyPriceMatters: "ACCUs are used by government, businesses and large emitters. Their price provides carbon-market context rather than a standard household upgrade discount.",
    officialUrl: "https://cer.gov.au/schemes/australian-carbon-credit-unit-scheme/australian-carbon-credit-units",
    colour: "#34d399",
  },
  {
    code: "SMC",
    name: "Safeguard Mechanism Credit unit",
    region: "Australia-wide",
    relevance: "Broader energy market",
    plainEnglish: "Rewards covered industrial facilities that reduce their emissions below the baseline set for them under the Safeguard Mechanism.",
    represents: "One tonne of carbon dioxide equivalent emissions below a facility's baseline. An SMC is a compliance credit, not an offset.",
    whyPriceMatters: "SMCs are mainly relevant to large industrial facilities managing Safeguard obligations, not household rebates.",
    officialUrl: "https://cer.gov.au/schemes/safeguard-mechanism/safeguard-mechanism-credit-units",
    colour: "#f472b6",
  },
];

const CERTIFICATE_CODE_SET = new Set<string>(CERTIFICATE_CODES);
const SOURCE_SERIES_PATTERN = /type:\s*["']scatter["'][\s\S]*?dataPoints:\s*(\[[^\]]*\])[\s\S]*?legendText:\s*["'](ESC|VEEC|STC|LGC|ACCU|PRC|SMC)["']/g;

function isCertificateCode(value: string): value is CertificateCode {
  return CERTIFICATE_CODE_SET.has(value);
}

function isoDateFromTimestamp(value: number): string {
  if (!Number.isFinite(value) || value < Date.UTC(2000, 0, 1) || value > Date.UTC(2100, 0, 1)) {
    throw new Error("The certificate source contained an invalid trade date.");
  }
  return new Date(value).toISOString().slice(0, 10);
}

export function parseDemandManagerCertificateHtml(html: string): CertificateTrade[] {
  if (!html || html.length > 3_000_000) throw new Error("The certificate source response was invalid.");

  const trades: CertificateTrade[] = [];
  const found = new Set<CertificateCode>();
  for (const match of html.matchAll(SOURCE_SERIES_PATTERN)) {
    const code = match[2];
    if (!isCertificateCode(code)) continue;
    let points: unknown;
    try {
      points = JSON.parse(match[1]);
    } catch {
      throw new Error(`The ${code} certificate history could not be read.`);
    }
    if (!Array.isArray(points) || points.length === 0) throw new Error(`The ${code} certificate history was empty.`);
    for (const point of points) {
      const x = Number((point as { x?: unknown }).x);
      const y = Number((point as { y?: unknown }).y);
      if (!Number.isFinite(y) || y <= 0 || y > 10_000) throw new Error(`The ${code} certificate history contained an invalid price.`);
      trades.push({ code, tradedOn: isoDateFromTimestamp(x), priceCents: Math.round(y * 100) });
    }
    found.add(code);
  }

  const missing = CERTIFICATE_CODES.filter((code) => !found.has(code));
  if (missing.length) throw new Error(`The certificate source did not include ${missing.join(", ")}.`);
  return trades;
}

export function collapseCertificateTradesByDay(trades: CertificateTrade[]): CertificateTrade[] {
  const daily = new Map<string, CertificateTrade>();
  for (const trade of trades) daily.set(`${trade.code}:${trade.tradedOn}`, trade);
  return [...daily.values()].sort((left, right) => left.code.localeCompare(right.code) || left.tradedOn.localeCompare(right.tradedOn));
}

export function isoDateMonthsBefore(date: Date, months: number): string {
  const firstOfTargetMonth = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth() - months, 1));
  const lastDayOfTargetMonth = new Date(Date.UTC(firstOfTargetMonth.getUTCFullYear(), firstOfTargetMonth.getUTCMonth() + 1, 0)).getUTCDate();
  const result = new Date(Date.UTC(firstOfTargetMonth.getUTCFullYear(), firstOfTargetMonth.getUTCMonth(), Math.min(date.getUTCDate(), lastDayOfTargetMonth)));
  return result.toISOString().slice(0, 10);
}
