import type { MemberEngagement, MemberEngagementBusiness } from './trade-member-engagement';

export type MemberAgreementKind = 'employee' | 'contractor';
export const AGREEMENT_TEMPLATE_VERSION = '2026-10-02';
export const AGREEMENT_GUIDANCE = {
  employee: 'https://www.fairwork.gov.au/employment-conditions/contracts',
  contractor: 'https://business.gov.au/people/contractors/prepare-a-contract',
} as const;
export const agreementTitle = (kind: MemberAgreementKind) => kind === 'employee' ? 'Employee agreement' : 'Contractor agreement';

/** Only agreed commercial terms enter a draft. Bank and super identifiers stay in the private record. */
export function memberAgreementTemplate(kind: MemberAgreementKind, businessName: string, personName: string, terms: MemberEngagement, business?: MemberEngagementBusiness): string {
  const frequency = { weekly: 'Weekly', fortnightly: 'Fortnightly', monthly: 'Monthly', per_job: 'Per job', by_agreement: 'By agreement', '': '[Payment frequency]' }[terms.paymentFrequency];
  const basis = { hourly: 'per hour', annual_salary: 'annual salary', per_job: 'per job', '': '' }[terms.rateBasis];
  const amount = terms.rateAmount && basis ? `AUD ${terms.rateAmount} ${basis}` : '[Agreed amount and pay basis]';
  const common = `PARTIES\nBusiness name (verify legal name): ${business?.businessName || businessName || '[Business legal name]'}\nBusiness ABN: ${business?.abn || '[Complete]'}\nBusiness address: ${business?.address || '[Complete]'}\n${kind === 'employee' ? 'Employee' : 'Contractor legal name'}: ${personName || '[Name]'}\n${kind === 'contractor' ? 'Contractor ABN and address' : 'Employee address'}: [Complete]\nStart date: ${terms.startDate || '[Start date]'}\n\n`;
  if (kind === 'employee') return common + `ROLE AND HOURS\nPosition, duties and workplace: [Complete]\nEmployment basis: [Full-time, part-time or casual; confirm any fixed term]\nOrdinary hours and roster: [Complete]\nAward or enterprise agreement and classification: [Identify applicable coverage]\n\nPAY\nAgreed base pay: ${amount}\nPay frequency: ${frequency}\nPayment method: ${terms.paymentMethod === 'bank_transfer' ? 'Bank transfer' : terms.paymentMethod === 'cash' ? 'Cash' : '[Agreed method]'}\nAllowances, overtime, penalties and any casual loading: [Specify applicable arrangements]\nThe agreed pay does not remove minimum statutory, award or agreement entitlements. Super contributions will be made where required.\n\nWORKING ARRANGEMENTS\nLeave, breaks, notice and other minimum conditions follow the applicable law, award or enterprise agreement.\nSafety, tools, expenses and relevant workplace policies: [Complete]\nProvide the information statements required for this employment.\nAdditional agreed terms: [Complete or remove]\n\nREVIEW AND SIGNATURES\nComplete all bracketed fields and check applicable entitlements before signing. Obtain advice for the particular role where needed. Each party receives a copy of the agreed document.\nBusiness representative name and position: ____________________\nBusiness signature: ____________________ Date: __________\nEmployee signature: ____________________ Date: __________`;
  return common + `SERVICES\nWork, deliverables and job/location: [Define]\nTiming and completion criteria: [Define]\nTools, materials, expenses and required licences/insurance: [Agree]\n\nFEES AND PAYMENT\nAgreed fee: ${amount}\nPayment timing: ${frequency}\nGST treatment, invoice requirements and payment due date: [Agree]\nDefine the priced job or milestone and any separately agreed rates. Record changes to scope, price or timing in writing before the varied work.\n\nWORKING ARRANGEMENTS\nSafety, access and coordination responsibilities: [Agree]\nConfidential information and ownership of work/materials: [Agree]\nThe parties retain their applicable legal obligations, including any super obligations. A contractor label does not determine legal worker status.\n\nENDING THE AGREEMENT AND DISPUTES\nNotice, unfinished work and payment for completed work: [Agree]\nDispute contacts and agreed resolution process: [Complete]\nAdditional terms: [Complete or remove]\n\nREVIEW AND SIGNATURES\nComplete all bracketed fields and review this agreement for the actual work before signing. Each party receives a copy.\nBusiness representative name and position: ____________________\nBusiness signature: ____________________ Date: __________\nContractor representative name and position: ____________________\nContractor signature: ____________________ Date: __________`;
}
