import Link from "next/link";
import { GuideShell, GuideSection } from "@/components/GuideShell";
import { buildPlatformMetadata } from "@/lib/public-site";

export const metadata = buildPlatformMetadata({
  path: "/guides",
  title: "Home Energy Guides and Support | Australian Energy Assessments",
  description: "Independent guidance for home comfort, electrification, solar, batteries, EV charging, rebates and project-ready decisions.",
});

export default function GuidesPage() {
  return <GuideShell label="Learn and prepare" title="Find the right evidence without opening ten tabs" introduction="Start with the decision you are making. Each guide explains what to check, what belongs in a written quote and which official source should confirm incentives or requirements.">
    <section className="guide-callout guide-callout-primary"><div><h2>Not sure which guide comes first?</h2><p>Build a private home energy roadmap from your goal, property situation and existing equipment. It puts the relevant comparisons, guides, assessment and project brief in order.</p></div><Link href="/plan">Build my roadmap</Link></section>
    <section className="guide-callout"><div><h2>What are STCs, VEECs and other energy certificates worth?</h2><p>Learn what each certificate represents, which ones can affect household upgrade discounts and how indicative reported prices have moved over the past six months.</p></div><Link href="/guides/certificate-prices">Open the certificate price tracker</Link></section>
    <section className="guide-callout"><div><h2>Need a NatHERS or BASIX assessment?</h2><p>Start with the dedicated assessment hub for new homes, existing homes and NSW BASIX projects, including the evidence to prepare and the official pathway to confirm.</p></div><Link href="/assessments">Explore assessment services</Link></section>
    <GuideSection eyebrow="Choose a guide" title="Start with the decision you are making"><div className="guide-card-grid">
      <article className="guide-card guide-card-wide"><span>Project preparation</span><h3>Know what the next step needs before committing</h3><p>Check urgent-replacement evidence, owner or strata permissions, renter-friendly boundaries and what each budget band should accomplish.</p><Link href="/guides/project-preparation">Open the project preparation guide</Link></article>
      <article className="guide-card guide-card-wide"><span>Home energy upgrades</span><h3>Work out what to improve first</h3><p>Start with safety, comfort and the building itself, then plan equipment, electrification, solar and batteries around your home.</p><Link href="/guides/home-energy-upgrades">Open the home energy upgrades guide</Link></article>
      <article className="guide-card"><span>Assessment checklist</span><h3>Get ready without collecting the wrong paperwork</h3><p>See what to prepare for plan-based NatHERS work, an on-site Home Energy Rating or a general energy audit.</p><Link href="/guides/prepare-for-home-energy-assessment">Open the assessment checklist</Link></article>
      <article className="guide-card"><span>Assessment costs</span><h3>Check whether a free program really applies</h3><p>Learn what is free, what still needs a quote and how to verify a current council or government offer.</p><Link href="/guides/free-home-energy-assessments">Open the assessment cost guide</Link></article>
      <article className="guide-card"><span>Myths and facts</span><h3>Get clear answers about ratings, bills and savings</h3><p>Separate what an assessment can show from what depends on your home, household and approval authority.</p><Link href="/guides/home-energy-assessment-myths">Open the myths and facts guide</Link></article>
      <article className="guide-card guide-card-wide"><span>Building approvals</span><h3>Understand NCC, NatHERS and BASIX</h3><p>See which system sets the rules, which one models the home and how NSW BASIX fits into the approval process.</p><Link href="/guides/ncc-nathers-basix">Open the NCC, NatHERS and BASIX guide</Link></article>
      <article className="guide-card guide-card-wide"><span>Ratings and certifications</span><h3>Know what a green building claim really means</h3><p>Compare NCC, NatHERS, BASIX, Home Energy Rating, Green Star and NABERS without treating their labels or star scales as interchangeable.</p><Link href="/guides/green-building-certifications-australia">Open the ratings and certifications guide</Link></article>
      <article className="guide-card"><span>Rooftop solar</span><h3>Match generation to your home</h3><p>Understand sizing, self-consumption, exports, site design, quote assumptions and installer checks.</p><Link href="/guides/solar">Open the solar guide</Link></article>
      <article className="guide-card"><span>Home batteries</span><h3>Test whether storage fits your load</h3><p>Understand usable capacity, power, backup, cycling, warranties, VPP terms and the current federal discount structure.</p><Link href="/guides/batteries">Open the battery guide</Link></article>
      <article className="guide-card"><span>Heating and cooling</span><h3>Reduce the load before sizing equipment</h3><p>Compare reverse-cycle systems using climate-zone performance, room needs, noise, installation details and realistic operating patterns.</p><Link href="/guides/heating">Open the heating guide</Link></article>
      <article className="guide-card"><span>Heat pumps</span><h3>Compare the right system for the job</h3><p>Understand reverse-cycle air conditioners and heat pump hot-water systems, including sizing, climate, noise and quote checks.</p><Link href="/guides/heat-pumps">Open the heat pump guide</Link></article>
      <article className="guide-card"><span>Hot water</span><h3>Match the system to household demand</h3><p>Compare heat pump, solar, storage and continuous-flow options using capacity, climate, tariffs, noise, backup and written quote evidence.</p><Link href="/guides/hot-water">Open the hot water guide</Link></article>
      <article className="guide-card guide-card-wide"><span>Building fabric</span><h3>Reduce unwanted heat flow and air leakage</h3><p>Assess insulation, draughts, ventilation, moisture, windows, safety and quote scope before replacing major heating or cooling equipment.</p><Link href="/guides/insulation-draught-proofing">Open the insulation guide</Link></article>
      <article className="guide-card"><span>Electric cooking</span><h3>Coordinate the appliance and enabling work</h3><p>Check induction cooking, cookware, circuits, ventilation, kitchen fit and safe gas decommissioning.</p><Link href="/guides/cooking">Open the cooking guide</Link></article>
      <article className="guide-card"><span>EV charging</span><h3>Match charging power to real driving</h3><p>Check daily range, parking, solar, tariffs, switchboard capacity, smart controls and strata approval.</p><Link href="/guides/ev-charging">Open the EV charging guide</Link></article>
    </div></GuideSection>
    <section className="guide-callout"><div><h2>Use your own load pattern where possible</h2><p>A household can use the same annual electricity as another home but at very different times. Half-hour meter data makes solar self-use and battery discharge estimates more representative.</p></div><Link href="/compare">Model solar and battery scenarios</Link></section>
    <section className="guide-callout"><div><h2>Check location-specific support</h2><p>Rebates, certificates, loans and provider discounts can have different rules. Choose your state or territory and confirm the official source before using an incentive in a quote.</p></div><Link href="/rebates">Open rebates and assistance</Link></section>
    <section className="guide-callout"><div><h2>Need a reliable starting point for supplier research?</h2><p>Use the independent government and community sources, then check the licence, product, scope, warranty and rebate evidence for the exact work.</p></div><Link href="/trusted-suppliers">Open trusted resources and supplier checks</Link></section>
    <section className="guide-callout"><div><h2>See why the evidence matters</h2><p>Worked examples show how timing, self-use and seasonal consumption can change an assessment, with the method and limitations visible.</p></div><Link href="/case-studies">View worked examples</Link></section>
  </GuideShell>;
}
