import assert from 'node:assert/strict';
import test from 'node:test';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {createHash} from 'node:crypto';
import ts from 'typescript';
import * as lifecycleSql from '../src/lib/creditex-job-lifecycle-sql.ts';
import * as delivery from '../src/lib/service-reminder-delivery.ts';
const NOW='2026-09-25T06:00:00.000Z',SHA='a'.repeat(64);
const trade={kind:'trade',uid:'manager',access:{ownerUid:'owner',actorUid:'manager',isOwner:true,jobScope:'team',canManageJobs:true,canManageFieldEvidence:true,canViewFieldEvidence:true}};
const admin={kind:'compliance',uid:'creditex',organisationId:'org',role:'admin'};
function fixture(t){
 const sqlite=new DatabaseSync(':memory:');t.after(()=>sqlite.close());sqlite.exec(`PRAGMA foreign_keys=ON;
 CREATE TABLE trade_work_orders(id TEXT PRIMARY KEY,firebase_uid TEXT,partner_type TEXT,work_number TEXT,title TEXT,stage TEXT,record_status TEXT,revision INTEGER,assignee_member_id TEXT,updated_at TEXT);
 CREATE TABLE trade_accounts(firebase_uid TEXT,business_name TEXT);
 CREATE TABLE trade_team_members(id TEXT,owner_uid TEXT,email TEXT,display_name TEXT,status TEXT);
 CREATE TABLE trade_work_order_compliance_intents(id TEXT PRIMARY KEY,status TEXT,compliance_organisation_id TEXT,work_order_id TEXT,installer_uid TEXT,revision INTEGER,intent_snapshot_sha256 TEXT,program_code TEXT,activity_template_id TEXT,compliance_case_id TEXT,intent_snapshot TEXT);
 CREATE TABLE trade_activity_field_records(id TEXT PRIMARY KEY,intent_id TEXT,work_order_id TEXT,owner_uid TEXT,organisation_id TEXT,revision INTEGER,status TEXT,pdf_sha256 TEXT,pdf_object_key TEXT,submitted_at TEXT,supersedes_record_id TEXT);
 CREATE TABLE trade_activity_field_record_versions(record_id TEXT,payload TEXT);
 CREATE TABLE compliance_activity_work_pack_instances(id TEXT PRIMARY KEY,organisation_id TEXT,work_order_id TEXT,compliance_intent_id TEXT,instance_key TEXT,revision INTEGER,status TEXT,supersedes_instance_id TEXT,created_by_uid TEXT,created_at TEXT);
 CREATE TABLE compliance_activity_work_pack_final_records(id TEXT,case_instance_id TEXT,organisation_id TEXT,pdf_sha256 TEXT,object_key TEXT);
 CREATE TABLE compliance_cases(id TEXT PRIMARY KEY,organisation_id TEXT,compliance_intent_id TEXT,work_order_id TEXT,installer_uid TEXT,revision INTEGER,status TEXT,evidence_status TEXT,updated_at TEXT);
 CREATE TABLE compliance_output_action_packets(id TEXT PRIMARY KEY,organisation_id TEXT,compliance_case_id TEXT,packet_sha256 TEXT,program_code TEXT,activity_template_id TEXT,case_revision INTEGER,work_pack_instance_key TEXT,work_pack_revision INTEGER,output_code TEXT,prepared_at TEXT);
 CREATE TABLE compliance_output_action_events(id TEXT PRIMARY KEY,organisation_id TEXT,packet_id TEXT,to_status TEXT,sequence INTEGER);
 CREATE TABLE compliance_output_dispatch_intents(packet_id TEXT,organisation_id TEXT,status TEXT);
 CREATE TABLE creditex_registry_results(id TEXT,organisation_id TEXT,packet_id TEXT,registry_status TEXT,source TEXT,occurred_at TEXT,created_at TEXT);
 CREATE TABLE creditex_registry_result_reviews(organisation_id TEXT,result_id TEXT,decision TEXT);
 CREATE TABLE creditex_registry_batch_items(organisation_id TEXT,packet_id TEXT);
 CREATE TABLE trade_crm_job_details(work_order_id TEXT,firebase_uid TEXT,pipeline_stage TEXT);
 CREATE TABLE trade_job_forms(work_order_id TEXT,firebase_uid TEXT,status TEXT);
 CREATE TABLE trade_work_order_events(id TEXT PRIMARY KEY,work_order_id TEXT,firebase_uid TEXT,event_type TEXT,summary TEXT NOT NULL,created_at TEXT);
 CREATE TABLE trade_crm_appointments(work_order_id TEXT,firebase_uid TEXT,status TEXT,revision INTEGER,updated_at TEXT);
 CREATE TABLE trade_crm_job_notes(id TEXT,work_order_id TEXT,firebase_uid TEXT,note_type TEXT,body TEXT,issue_status TEXT,created_at TEXT,updated_at TEXT);
 INSERT INTO trade_work_orders VALUES('job','owner','installer','TLJ-123','Installation','completed','active',1,'tech','${NOW}');
 INSERT INTO trade_accounts VALUES('owner','Trade Pty Ltd');
 INSERT INTO trade_team_members VALUES('tech','owner','tech@example.test','Technician','active');
 ALTER TABLE trade_work_orders ADD COLUMN scheduled_start TEXT DEFAULT '';
 ALTER TABLE trade_work_orders ADD COLUMN scheduled_end TEXT DEFAULT '';
 `);sqlite.exec(readFileSync(new URL('../drizzle/0193_creditex_job_lifecycle.sql',import.meta.url),'utf8'));
 class Statement{constructor(sql,values=[]){this.sql=sql;this.values=values;}bind(...v){return new Statement(this.sql,v);}async first(){return sqlite.prepare(this.sql).get(...this.values)||null;}async all(){return {results:sqlite.prepare(this.sql).all(...this.values)};}runSync(){return {meta:{changes:Number(sqlite.prepare(this.sql).run(...this.values).changes)}};}async run(){return this.runSync();}}
 let beforeBatch;
 const db={prepare:sql=>new Statement(sql),async batch(statements){if(beforeBatch){const fn=beforeBatch;beforeBatch=null;fn();}sqlite.exec('BEGIN');try{const r=statements.map(s=>s.runSync());sqlite.exec('COMMIT');return r;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
 const dependencies={'node:crypto':{createHash},'./trade-team-sync-server':{jobSyncChangeStatements:()=>[]},'./creditex-job-lifecycle-sql':lifecycleSql,'./service-reminder-delivery':delivery,
 './trade-job-cancellation-server':{cancelledJobAppointmentsStatement:(db,owner,job,now)=>db.prepare(`UPDATE trade_crm_appointments SET status='cancelled',revision=revision+1,updated_at=? WHERE work_order_id=? AND firebase_uid=? AND status='scheduled'`).bind(now,job,owner),reconcileCancelledJobCalendars:async()=>({attempted:0,synced:0,failed:0})},
 './creditex-activity-work-pack-server':{prepareCreditexCorrectionWorkPackStatements:async()=>[]},
 './trade-activity-forms-server':{prepareFieldCorrectionStatements:async(db,input)=>{const sources=JSON.parse(input.sourceSnapshot).records.filter(r=>r.kind==='field');return sources.map(s=>db.prepare(`INSERT INTO trade_activity_field_records SELECT id||'-correction',intent_id,work_order_id,owner_uid,organisation_id,revision+1,'draft','','','',id FROM trade_activity_field_records WHERE id=?`).bind(s.id));}}};
 const m={exports:{}};new Function('require','module','exports',ts.transpileModule(readFileSync(new URL('../src/lib/creditex-job-lifecycle-server.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(key=>{assert.ok(key in dependencies,key);return dependencies[key];},m,m.exports);
 const service=m.exports;const sent=[];const options={now:()=>NOW,send:async m=>{sent.push(m);return {provider:'resend',providerMessageId:'email-accepted',providerStatus:'sent'};}};
 function intent(id='intent'){sqlite.prepare('INSERT INTO trade_work_order_compliance_intents VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,'planned','org','job','owner',1,SHA,'VEU','activity','case-'+id,JSON.stringify({program:{claimOutputCode:'VEEC'}}));sqlite.prepare('INSERT INTO trade_activity_field_records VALUES(?,?,?,?,?,?,?,?,?,?,?)').run('field-'+id,id,'job','owner','org',1,'submitted_for_creditex_review',SHA,'private.pdf',NOW,null);sqlite.prepare('INSERT INTO compliance_cases VALUES(?,?,?,?,?,?,?,?,?)').run('case-'+id,'org',id,'job','owner',1,'ready_for_submission','verified',NOW);}
 async function input(action='reviewed'){const state=await service.loadTradeJobReview(db,trade,'job');return {workOrderId:'job',action,note:action==='reviewed'?'':'Fix the unit label',requestId:crypto.randomUUID(),expectedRevision:state.revision,expectedSourceSha256:state.sourceSha256};}
 async function lifecycle(action,more={}){const state=await service.loadJobLifecycle(db,admin,'intent');return {intentId:'intent',action,note:'Checked the records',requestId:crypto.randomUUID(),expectedRevision:state.revision,...more};}
 function packet(){sqlite.prepare('INSERT INTO compliance_output_action_packets VALUES(?,?,?,?,?,?,?,?,?,?,?)').run('packet','org','case-intent',SHA,'VEU','activity',1,'pack',1,'VEEC','2026-09-24T00:00:00.000Z');sqlite.prepare('INSERT INTO compliance_output_action_events VALUES(?,?,?,?,?)').run('event','org','packet','submitted',1);}
 return {sqlite,db,service,options,sent,intent,input,lifecycle,packet,intercept:fn=>beforeBatch=fn};
}
test('whole-job business pass binds all current sources and owner scope',async t=>{const f=fixture(t);f.intent();f.intent('second');const result=await f.service.reviewTradeJob(f.db,trade,await f.input(),f.options);assert.equal(result.reviewed,true);assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM creditex_job_lifecycle_events').get().n,2);await assert.rejects(f.service.loadJobLifecycle(f.db,{...admin,organisationId:'elsewhere'},'intent'),e=>e.status===404);await assert.rejects(f.service.reviewTradeJob(f.db,{...trade,access:{...trade.access,fieldSessionId:'field'}},await f.input(),f.options),e=>e.status===403);});
test('changed source atomically rejects pass without partial history',async t=>{const f=fixture(t);f.intent();const input=await f.input();f.intercept(()=>f.sqlite.exec(`UPDATE trade_activity_field_records SET revision=2`));await assert.rejects(f.service.reviewTradeJob(f.db,trade,input,f.options),e=>e.code==='JOB_REVIEW_SOURCE_CHANGED');assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM creditex_job_lifecycle_events').get().n,0);assert.equal(f.sqlite.prepare('SELECT revision FROM trade_work_orders').get().revision,1);});
test('correction preserves signed original, creates draft, invalidates audit and queues trusted technician email',async t=>{const f=fixture(t);f.intent();const input=await f.input('correction_required');const result=await f.service.reviewTradeJob(f.db,trade,input,f.options);assert.equal(result.canReview,false);assert.equal(f.sqlite.prepare(`SELECT status,pdf_object_key FROM trade_activity_field_records WHERE id='field-intent'`).get().pdf_object_key,'private.pdf');assert.equal(f.sqlite.prepare('SELECT revision,status,evidence_status FROM compliance_cases').get().revision,2);assert.equal(f.sqlite.prepare('SELECT stage FROM trade_work_orders').get().stage,'in_progress');assert.equal(f.sent[0].recipient,'tech@example.test');assert.match(f.sent[0].body,/TLJ-123/);assert.match(f.sent[0].body,/Fix the unit label/);assert.equal(result.notifications[0].status,'accepted');await f.service.reviewTradeJob(f.db,trade,input,f.options);assert.equal(f.sent.length,1);assert.throws(()=>f.sqlite.exec(`DELETE FROM creditex_job_lifecycle_events`),/HISTORY_RETAINED/);assert.throws(()=>f.sqlite.exec(`UPDATE creditex_job_lifecycle_events SET note='changed'`),/HISTORY_IMMUTABLE/);});
test('correction needs notes and approved reviewer access; Creditex correction names Creditex',async t=>{const f=fixture(t);f.intent();const input=await f.input('correction_required');await assert.rejects(f.service.reviewTradeJob(f.db,trade,{...input,note:''},f.options),e=>e.status===400);const state=await f.service.loadJobLifecycle(f.db,admin,'intent');await f.service.mutateJobLifecycle(f.db,admin,{...input,intentId:'intent',expectedCorrectionSourceSha256:state.correctionSourceSha256},f.options);assert.match(f.sent[0].body,/Creditex has returned/);});
test('failed email remains visible and retry uses same provider key',async t=>{const f=fixture(t);f.intent();let key;const result=await f.service.reviewTradeJob(f.db,trade,await f.input('correction_required'),{...f.options,send:async m=>{key=m.idempotencyKey;throw new delivery.ReminderProviderDeliveryError('indeterminate','connection lost');}});assert.equal(result.notifications[0].status,'uncertain');await f.service.dispatchJobCorrectionEmail(f.db,trade,result.notifications[0].id,f.options);assert.equal(f.sent[0].idempotencyKey,key);assert.equal(f.sqlite.prepare('SELECT status FROM creditex_job_correction_deliveries').get().status,'accepted');});
test('completed jobs cannot cancel; bin and restore preserve signed evidence at any stage',async t=>{const f=fixture(t);f.intent();await assert.rejects(f.service.mutateJobLifecycle(f.db,admin,await f.lifecycle('cancelled'),f.options),e=>e.code==='JOB_CANCEL_COMPLETED');await f.service.mutateJobLifecycle(f.db,admin,await f.lifecycle('deleted'),f.options);assert.equal(f.sqlite.prepare('SELECT record_status FROM trade_work_orders').get().record_status,'archived');assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM trade_activity_field_records').get().n,1);await f.service.mutateJobLifecycle(f.db,admin,await f.lifecycle('restored'),f.options);assert.equal(f.sqlite.prepare('SELECT record_status FROM trade_work_orders').get().record_status,'active');});
test('payout requires actual lodgement and binds trusted business recipient, never regulator fee',async t=>{const f=fixture(t);f.intent();const more={reference:'BANK-123',amount:'123.45',paidOn:'2026-09-25',recipientUid:'attacker'};await assert.rejects(f.service.mutateJobLifecycle(f.db,admin,await f.lifecycle('payout_recorded',more),f.options),e=>e.code==='JOB_PAYOUT_SUBMISSION_REQUIRED');f.packet();await f.service.mutateJobLifecycle(f.db,admin,await f.lifecycle('payout_recorded',more),f.options);const event=f.sqlite.prepare(`SELECT recipient_uid,amount_minor FROM creditex_job_lifecycle_events WHERE action='payout_recorded'`).get();assert.equal(event.recipient_uid,'owner');assert.equal(event.amount_minor,12345);});
test('government rejection blocks payout and actual lodgement blocks correction',async t=>{const f=fixture(t);f.intent();f.packet();f.sqlite.exec(`INSERT INTO creditex_registry_results VALUES('result','org','packet','rejected','rec_public_register','${NOW}','${NOW}')`);assert.equal((await f.service.loadJobLifecycle(f.db,admin,'intent')).capabilities.canRecordPayout,false);await assert.rejects(f.service.reviewTradeJob(f.db,trade,await f.input('correction_required'),f.options),e=>e.code==='JOB_REVIEW_ALREADY_LODGED');});
test('government rejection arriving during payout write rolls the action back',async t=>{const f=fixture(t);f.intent();f.packet();const input=await f.lifecycle('payout_recorded',{reference:'BANK-1',amount:'100',paidOn:'2026-09-25'});f.intercept(()=>f.sqlite.exec(`INSERT INTO creditex_registry_results VALUES('r','org','packet','rejected','rec_public_register','${NOW}','${NOW}')`));await assert.rejects(f.service.mutateJobLifecycle(f.db,admin,input,f.options),e=>e.code==='JOB_LIFECYCLE_CHANGED');assert.equal(f.sqlite.prepare(`SELECT COUNT(*) n FROM creditex_job_lifecycle_events WHERE action='payout_recorded'`).get().n,0);});
test('dispatching and uncertain registry requests prevent changing completed source, including race',async t=>{const f=fixture(t);f.intent();f.packet();f.sqlite.exec(`DELETE FROM compliance_output_action_events;INSERT INTO compliance_output_dispatch_intents VALUES('packet','org','uncertain')`);await assert.rejects(f.service.reviewTradeJob(f.db,trade,await f.input('correction_required'),f.options),e=>e.code==='JOB_REVIEW_ALREADY_LODGED');f.sqlite.exec('DELETE FROM compliance_output_dispatch_intents');const input=await f.input();f.intercept(()=>f.sqlite.exec(`INSERT INTO compliance_output_dispatch_intents VALUES('packet','org','dispatching')`));await assert.rejects(f.service.reviewTradeJob(f.db,trade,input,f.options),e=>e.code==='JOB_REVIEW_SOURCE_CHANGED');assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM creditex_job_lifecycle_events').get().n,0);});
test('notification retry enforces real assigned-job scope and selected job association',async t=>{const f=fixture(t);f.intent();const result=await f.service.reviewTradeJob(f.db,trade,await f.input('correction_required'),{...f.options,send:async()=>{throw new Error('No email');}});const manager={...trade,access:{...trade.access,isOwner:false,jobScope:'own',memberId:'other'}};await assert.rejects(f.service.dispatchJobCorrectionEmail(f.db,manager,result.notifications[0].id,f.options),e=>e.status===404);await assert.rejects(f.service.dispatchJobCorrectionEmail(f.db,trade,result.notifications[0].id,{...f.options,expectedWorkOrderId:'other-job'}),e=>e.status===404);assert.equal(f.sent.length,0);});
test('Australian payout date accepts today after local midnight',async t=>{const f=fixture(t);f.intent();f.packet();await f.service.mutateJobLifecycle(f.db,admin,await f.lifecycle('payout_recorded',{reference:'BANK-1',amount:'100',paidOn:'2026-09-26'}),{now:()=> '2026-09-25T15:00:00.000Z'});assert.equal(f.sqlite.prepare('SELECT occurred_at FROM creditex_job_lifecycle_events').get().occurred_at,'2026-09-26T00:00:00.000Z');});
test('cancellation is allowed before completion and still denied after stage reversal',async t=>{const f=fixture(t);f.intent();f.sqlite.exec(`UPDATE trade_work_orders SET stage='scheduled';UPDATE trade_activity_field_records SET status='draft',submitted_at='',pdf_object_key='',pdf_sha256=''`);await f.service.mutateJobLifecycle(f.db,admin,await f.lifecycle('cancelled'),f.options);assert.equal(f.sqlite.prepare('SELECT stage FROM trade_work_orders').get().stage,'cancelled');});
