import assert from 'node:assert/strict';
import test from 'node:test';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
import * as jsx from 'react/jsx-runtime';
function harness(){let index=0,slots=[],effects=[],cleanups=[],lastKey,jobId='job',deferredGet,releaseGet;const requests=[];
 const state={workOrderId:'job',revision:1,sourceSha256:'source',canReview:true,reviewed:false,reason:'',activities:[{complete:true}],notifications:[],history:[]};
 const changed=(old,next)=>!old||old.length!==next.length||old.some((v,i)=>v!==next[i]);
 const react={useState(value){const i=index++,currentSlots=slots;if(!(i in currentSlots))currentSlots[i]=value;return[currentSlots[i],v=>currentSlots[i]=typeof v==='function'?v(currentSlots[i]):v];},useRef(value){const i=index++;if(!(i in slots))slots[i]={current:value};return slots[i];},useCallback(fn,deps){const i=index++;if(changed(slots[i]?.deps,deps))slots[i]={fn,deps};return slots[i].fn;},useEffect(fn,deps){const i=index++;if(changed(slots[i],deps)){effects.push(()=>{cleanups[i]?.();cleanups[i]=fn();});slots[i]=deps;}}};
 const m={exports:{}};new Function('require','module','exports',ts.transpileModule(readFileSync(new URL('../src/components/TradeJobReviewPanel.tsx',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText)(key=>key==='react'?react:key==='react/jsx-runtime'?jsx:{default:{panel:'panel'}},m,m.exports);
 const user={getIdToken:async()=> 'token'};let failNext=false;const fetcher=async(url,options={})=>{if(options.method==='POST'){requests.push(JSON.parse(options.body));if(failNext){failNext=false;throw new Error('Connection lost');}return Response.json({state:{...state,reviewed:true}});}const workOrderId=new URL(url,'https://test').searchParams.get('workOrderId');if(deferredGet===workOrderId){deferredGet=null;await new Promise(r=>releaseGet=r);}return Response.json({state:{...state,workOrderId}});};
 const render=()=>{const component=m.exports.TradeJobReviewPanel({user,workOrderId:jobId,onChanged:()=>{}});if(lastKey!==undefined&&lastKey!==component.key){cleanups.forEach(fn=>fn?.());slots=[];effects=[];cleanups=[];}lastKey=component.key;index=0;return component.type(component.props);};
 const elements=(node,result=[])=>{if(!node||typeof node!=='object')return result;if(node.type)result.push(node);const c=node.props?.children;if(Array.isArray(c))c.flat(Infinity).forEach(n=>elements(n,result));else elements(c,result);return result;};
 return{state,requests,render,fetcher,fail(){failNext=true;},deferGet(){deferredGet='job';},releaseGet(){releaseGet();},current(){return slots[0];},setJob(id){jobId=id;},async ready(){render();effects.splice(0).forEach(fn=>fn());await new Promise(r=>setImmediate(r));},button(label){return elements(render()).find(n=>n.type==='button'&&n.props.children===label);},textarea(){return elements(render()).find(n=>n.type==='textarea');}};
}
test('Pass saves once for a rapid double click',async()=>{const h=harness(),original=globalThis.fetch;globalThis.fetch=h.fetcher;try{await h.ready();const pass=h.button('Pass');pass.props.onClick();pass.props.onClick();await new Promise(r=>setImmediate(r));assert.equal(h.requests.length,1);assert.equal(h.requests[0].action,'reviewed');assert.equal(h.button('Pass').props.disabled,true);}finally{globalThis.fetch=original;}});
test('uncertain request retry reuses same request ID and notes',async()=>{const h=harness(),original=globalThis.fetch;globalThis.fetch=h.fetcher;try{await h.ready();h.fail();h.button('Pass').props.onClick();await new Promise(r=>setImmediate(r));h.button('Pass').props.onClick();await new Promise(r=>setImmediate(r));assert.equal(h.requests.length,2);assert.deepEqual(h.requests[0],h.requests[1]);}finally{globalThis.fetch=original;}});
test('Correction required needs notes, while unavailable review disables both decisions',async()=>{const h=harness(),original=globalThis.fetch;globalThis.fetch=h.fetcher;try{await h.ready();assert.equal(h.button('Correction required').props.disabled,true);h.textarea().props.onChange({target:{value:'Fix label'}});assert.equal(h.button('Correction required').props.disabled,false);h.button('Correction required').props.onClick();await new Promise(r=>setImmediate(r));assert.equal(h.requests[0].note,'Fix label');assert.equal(h.requests[0].action,'correction_required');}finally{globalThis.fetch=original;}});
test('late response from previous job cannot replace selected job or retain its notes',async()=>{const h=harness(),original=globalThis.fetch;globalThis.fetch=h.fetcher;try{h.deferGet();await h.ready();h.setJob('next-job');await h.ready();assert.equal(h.current().workOrderId,'next-job');h.releaseGet();await new Promise(r=>setImmediate(r));assert.equal(h.current().workOrderId,'next-job');assert.equal(h.textarea().props.value,'');}finally{globalThis.fetch=original;}});
