import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
import { ENERGY_SERVICE_IDS } from '../src/lib/energy-service-catalogue.mjs';
import { normalizeTradeFormAnswers, tradeFormCompletion, visibleTradeFormFields } from '../src/lib/trade-form-library.mjs';
const read = path => fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
function compile(file, imports = {}) { const result = { exports: {} }; const code = ts.transpileModule(read(file), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText; new Function('require','module','exports',code)(key => { assert.ok(imports[key], key); return imports[key]; },result,result.exports); return result.exports; }
const design = compile('src/lib/trade-business-form-design.ts');
const { cleanTradeFormTemplateInput: clean } = compile('src/lib/trade-form-template-input.ts', { './admin-server': { cleanAdminText: (value, length) => typeof value === 'string' ? value.trim().slice(0,length) : '' }, './energy-service-catalogue.mjs': { ENERGY_SERVICE_IDS } });
const base = { templateKey:'business-demo', version:1, name:'Test', description:'Test', guidance:'Complete the questions', jurisdiction:'AU', categories:['other'], fields:[{key:'start',label:'Issue found?',type:'select',required:true,options:['Yes','No'],section:'Start',phase:'before'}, {key:'details',label:'Details',type:'textarea',required:true,section:'Finish',phase:'after',condition:{fieldKey:'start',equals:'Yes'}}] };
test('business pages and direct conditions survive validation and designer round trip',()=>{const value=clean(base);assert.equal(value.fields[1].phase,'after');assert.deepEqual(value.fields[1].condition,{fieldKey:'start',equals:'Yes'});const template={...value,id:'one',updatedAt:'now'};assert.deepEqual(design.applyBusinessFormDesign(template,design.businessFormDesign(template)).fields, value.fields.map(field=>({...field,condition:field.condition})));});
test('business condition boundary rejects future, cyclic, unknown, compound and invalid values',()=>{for(const condition of [{fieldKey:'details',equals:'Yes'},{fieldKey:'outside',equals:'Yes'},{fieldKey:'start',equals:'Fake'},{fieldKey:'start',equals:'Yes',notEquals:'No'},{all:[{fieldKey:'start',equals:'Yes'}]},{fieldKey:'start',lessThanOrEqual:3}]) assert.throws(()=>clean({...base,fields:[base.fields[0],{...base.fields[1],condition}]}),/INVALID_CONDITION/);assert.throws(()=>clean({...base,fields:[{...base.fields[0],phase:'after'},{...base.fields[1],phase:'before'}]}),/INVALID_CONDITION/);});
test('hidden required answers do not block completion and stale hidden data is removed',()=>{const template=clean(base);assert.deepEqual(normalizeTradeFormAnswers(template,{start:'No',details:'Old answer',extra:'foreign'}),{start:'No'});assert.equal(tradeFormCompletion(template,{start:'No'}).ready,true);assert.deepEqual(tradeFormCompletion(template,{start:'Yes'}).missing,['Details']);assert.equal(tradeFormCompletion(template,{start:'Yes',details:'Done'}).ready,true);assert.equal(tradeFormCompletion(template,{start:'Fake',details:'Done'}).ready,false);});
test('hidden conditions propagate through multiple dependent questions',()=>{const template={fields:[base.fields[0],{key:'second',type:'select',options:['A','B'],condition:{fieldKey:'start',equals:'Yes'}},{key:'third',type:'text',required:true,condition:{fieldKey:'second',notEquals:'B'}}]};assert.deepEqual(visibleTradeFormFields(template,{start:'No',second:'A',third:'Old'}).map(field=>field.key),['start']);assert.deepEqual(normalizeTradeFormAnswers(template,{start:'No',second:'A',third:'Old'}),{start:'No'});assert.equal(tradeFormCompletion(template,{start:'No',second:'A'}).ready,true);});
test('legacy forms retain their required checkbox and date validation',()=>{const template={fields:[{key:'confirm',label:'Confirm',type:'checkbox',required:true},{key:'date',label:'Date',type:'date',required:true}]};assert.equal(tradeFormCompletion(template,{confirm:false,date:'2026-10-02'}).ready,false);assert.equal(tradeFormCompletion(template,{confirm:true,date:'2026-02-30'}).ready,false);assert.equal(tradeFormCompletion(template,{confirm:true,date:'2026-10-02'}).ready,true);});
test('pages split at eight and preserve before-work and after-work grouping',()=>{const fields=Array.from({length:10},(_,i)=>({key:`q${i}`,label:`Q${i}`,type:'text',required:false,section:'Checks',phase:'before'}));fields.splice(1,0,{key:'finish',label:'Finish',type:'text',required:false,section:'Completed',phase:'after'});const pages=design.businessFormPages(fields);assert.deepEqual(pages.map(page=>page.fields.length),[8,2,1]);assert.equal(pages[2].key,'finish');assert.match(pages[2].title,/After work/);});
test('both sidebars expose Forms directly and authoring is removed from the job panel',()=>{for(const name of ['DirectTradeDashboard','TradeTeamPortal']){const source=read(`src/components/${name}.tsx`);assert.match(source,/<span>Forms<\/span>/);assert.match(source,/<TradeFormsWorkspace user=\{user\} onRegisterLeave=\{registerMapSave\}/);}assert.doesNotMatch(read('src/components/TradeJobFormsPanel.tsx'),/TradeBusinessFormEditor/);assert.match(read('src/components/InstallerCrmWorkspace.tsx'),/<TradeJobFormsPanel/);});
const mfaResponse=()=>null;
class TradeBusinessContextError extends Error { status=403; }
function catalogueRoute(allowed=true) { const calls=[];return {calls,route:compile('src/app/api/trade-form-catalogue/route.ts',{'../../../../db':{getD1:()=>({prepare:sql=>({bind:(...bindings)=>({first:async()=>{calls.push({sql,bindings});return null;}})})})},'@/lib/admin-server':{adminJson:(value,status=200)=>Response.json(value,{status}),sameOrigin:()=>true,mfaErrorResponse:mfaResponse},'@/lib/trade-team-server':{requireInstallerTeamAccess:async()=>{if(!allowed)throw new Error('TEAM_ACCESS_REQUIRED');return {ownerUid:'a'};}},'@/lib/trade-business-context-server':{TradeBusinessContextError},'@/lib/creditex-official-source-custody-server':{resolveActiveCreditexOfficialSourceOrganisation:async()=> 'official'},'@/lib/trade-activity-forms-library':{activityFieldCatalogue:()=>[{activityTemplateId:'official-one',title:'Official one'}],defaultActivityFieldForm:id=>({id,variantId:'base',fields:[]}),applyDefaultActivityFormPolicy:form=>form}})}; }
test('compliance catalogue requires active business login before returning definitions',async()=>{const fixture=catalogueRoute(false);const response=await fixture.route.GET(new Request('https://tlink.test/api/trade-form-catalogue'));assert.equal(response.status,403);assert.equal(fixture.calls.length,0);});
test('compliance preview reads current official masters only, never drafts or job answers',async()=>{const fixture=catalogueRoute();const response=await fixture.route.GET(new Request('https://tlink.test/api/trade-form-catalogue?activityTemplateId=official-one'));assert.equal(response.status,200);assert.deepEqual(fixture.calls[0].bindings,['official','official-one','base']);assert.doesNotMatch(fixture.calls[0].sql,/draft|records|answers/);assert.match(fixture.calls[0].sql,/ORDER BY version DESC LIMIT 1/);assert.equal(fixture.route.POST,undefined);});
test('unknown official form identifier does not query master storage',async()=>{const fixture=catalogueRoute();const response=await fixture.route.GET(new Request('https://tlink.test/api/trade-form-catalogue?activityTemplateId=business-secret'));assert.equal(response.status,404);assert.equal(fixture.calls.length,0);});

test('checkbox preview enforces checked confirmation without locking the designer',()=>{const template={...base,id:'one',updatedAt:'now',fields:[{key:'confirm',label:'Confirm',type:'checkbox',required:true}]};assert.equal(design.businessFormPreview(template).fields[0].requiredValue,true);assert.equal(design.businessFormDesign(template).fields[0].requiredValue,undefined);});
