import type { Metadata } from "next";
import { SiteFooter, SiteHeader } from "@/components/ComparatorChrome";

export const metadata: Metadata = {
  title: "Direct Trade membership and referrals | Australian Energy Assessments",
  description: "Compare transparent installer and wholesaler membership pricing, matching rules and the planned referral reward.",
};

const plans = [
  { audience: "Trades and installers", cadence: "Annual", monthly: "$99", billed: "$1,188 billed once per year", value: "Best value" },
  { audience: "Trades and installers", cadence: "Month to month", monthly: "$199", billed: "Charged monthly", value: "Flexible" },
  { audience: "Suppliers and wholesalers", cadence: "Annual", monthly: "$199", billed: "$2,388 billed once per year", value: "Best value" },
  { audience: "Suppliers and wholesalers", cadence: "Month to month", monthly: "$399", billed: "Charged monthly", value: "Flexible" },
];

export default function DirectTradeMembershipPage() {
  return <main className="wrap direct-trade-membership-page">
    <SiteHeader active="direct-trade-membership" />
    <header className="membership-hero"><div><span>Direct Trade membership</span><h1>One subscription, no per-lead fees</h1><p>Membership supports verification, the business dashboard and fair matching. It does not buy ranking, guarantee opportunities or add a separate charge each time a suitable project is assigned.</p><div><a className="btn" href="/direct-trade/partners">Create a business profile</a><a className="btn ghost" href="/direct-trade/standards">Read the marketplace standards</a></div></div><aside><strong>Billing is not active yet</strong><p>These are the planned launch prices. Stripe is not connected and the site is not collecting payment details.</p><span>All prices include GST</span></aside></header>
    <section className="membership-plan-section" aria-labelledby="membership-plan-title"><div className="guide-section-heading"><span>Planned pricing</span><h2 id="membership-plan-title">Choose the role and billing cadence</h2><p>Annual plans show the monthly equivalent and are charged once per year.</p></div><div className="membership-plan-grid">{plans.map((plan) => <article className={plan.cadence === "Annual" ? "recommended" : ""} key={`${plan.audience}-${plan.cadence}`}><span>{plan.value}</span><small>{plan.audience}</small><h3>{plan.cadence}</h3><strong>{plan.monthly}<em>/month</em></strong><p>{plan.billed}, including GST.</p><ul><li>Dashboard access after launch</li><li>Verification pathway for the business role</li><li>Suitable opportunity matching after approval</li><li>No individual lead fee or paid placement</li></ul><button disabled type="button">Stripe billing coming later</button></article>)}</div></section>
    <section className="membership-included" aria-labelledby="membership-included-title"><div><span>Same marketplace rules</span><h2 id="membership-included-title">Price does not change matching priority</h2><p>Annual and month-to-month members follow the same verification and matching rules. Location, work type, verified capability, service coverage and availability guide a connection.</p></div><div className="membership-rule-grid"><article><strong>No lead auction</strong><p>Businesses do not bid against each other to receive a household brief.</p></article><article><strong>No paid ranking</strong><p>A higher payment does not move a business ahead of a better project fit.</p></article><article><strong>No volume promise</strong><p>Membership cannot guarantee how many suitable opportunities exist in a location.</p></article><article><strong>Household choice</strong><p>The household remains free to compare, ask questions and decline.</p></article></div></section>
    <section className="membership-referral" aria-labelledby="membership-referral-title"><div><span>Planned referral reward</span><h2 id="membership-referral-title">A month of membership credit for both businesses</h2><p>Every paying member will receive a unique referral code. When a new eligible business uses that code, starts a paid membership and its first payment clears, both businesses receive one month of membership credit.</p></div><aside><strong>Before a credit is issued</strong><ul><li>The referred business must be new and independently eligible</li><li>The first paid invoice must clear and remain valid</li><li>Self-referrals and duplicate businesses are excluded</li><li>Credits apply to membership invoices and are not cash</li><li>Annual-plan credit treatment will be confirmed in the final terms</li></ul></aside></section>
    <section className="membership-launch-boundary"><div><span>Before payment launch</span><h2>Terms and billing controls come first</h2><p>Stripe Checkout, subscription management, webhook-confirmed billing status, tax invoices, cancellation terms, refund rules and referral conditions must be completed and tested before production payments are enabled.</p></div><a className="btn" href="/direct-trade/dashboard">Open the dashboard</a></section>
    <SiteFooter>Membership pricing does not replace licensing, accreditation, insurance, product compliance, marketplace verification or each participant&apos;s legal obligations.</SiteFooter>
  </main>;
}
