import { GuideShell, GuideSection } from "@/components/GuideShell";

export const metadata = {
  title: "Electric Cooking Guide | Australian Energy Assessments",
  description: "Independent guidance for planning an induction cooktop and electric oven upgrade in an Australian home.",
};

export default function CookingGuidePage() {
  return <GuideShell label="Electric cooking guide" title="Plan the appliance, electrical work and kitchen fit together" introduction="Moving from gas cooking is more than choosing a cooktop. Check the household's cooking needs, cookware, ventilation, electrical capacity, bench opening and gas decommissioning before accepting a quote.">
    <GuideSection eyebrow="Start with the kitchen" title="Confirm what must fit and how it will be used"><div className="guide-principle-grid"><article><strong>Cooking pattern</strong><p>Record the number and size of zones normally used, oven needs, high-heat cooking and any accessibility controls that matter.</p></article><article><strong>Physical fit</strong><p>Measure the appliance opening, bench depth, clearances and cabinet ventilation. A nominal cooktop width does not prove the cut-out will fit.</p></article><article><strong>Electrical capacity</strong><p>Ask a licensed electrician to assess the circuit, switchboard, available supply and whether demand control or other enabling work is needed.</p></article></div></GuideSection>
    <GuideSection eyebrow="Before choosing" title="Separate product features from installation requirements"><div className="guide-two-column"><div><h3>Induction cooktop</h3><p>Induction heats compatible cookware through a magnetic field. Compare zone layout, controls, low-power stability, power sharing, surface protection and service support.</p><ul><li>Test existing pans with a magnet</li><li>Check the maximum connected load</li><li>Confirm child lock and control accessibility</li><li>Ask how power sharing affects simultaneous zones</li></ul></div><div><h3>Oven and ventilation</h3><p>Confirm oven capacity, cooking modes, cleaning method, circuit requirements and the ventilation needed for heat, steam, grease and moisture.</p><ul><li>Include any cabinet modification</li><li>Retain effective kitchen exhaust</li><li>Confirm plug-in or hard-wired connection</li><li>Include safe gas isolation and removal</li></ul></div></div></GuideSection>
    <GuideSection eyebrow="Written quote checklist" title="Make the complete changeover visible"><ul className="guide-checklist"><li>Exact cooktop and oven model numbers</li><li>Appliance dimensions and required cut-out</li><li>New circuit, cabling and protective devices</li><li>Switchboard or supply work included or excluded</li><li>Bench and cabinet alterations</li><li>Gas isolation, capping and appliance removal</li><li>Testing, certificates and handover</li><li>Product and workmanship warranties</li></ul><div className="guide-source-links"><a href="https://www.energy.gov.au/households/electrification" target="_blank" rel="noreferrer">Australian Government electrification guidance</a><a href="https://www.energyrating.gov.au/consumer-information" target="_blank" rel="noreferrer">Check current appliance energy guidance</a></div></GuideSection>
  </GuideShell>;
}
