"use client";
import { useState } from "react";
import type { CouncilVeuPeriodKey, CouncilVeuReport } from "@/lib/council-veu";
import { CouncilIcon, CouncilPanel, councilDate, councilNumber } from "./CouncilPrimitives";
import styles from "./CouncilVeu.module.css";
import workspace from "./CouncilWorkspace.module.css";

export type CouncilVeuState = { report: CouncilVeuReport | null; loading: boolean; error: string };
export function CouncilVeu({state,period,onPeriodChange,onRefresh,compact=false}:{state:CouncilVeuState;period:CouncilVeuPeriodKey;onPeriodChange:(value:CouncilVeuPeriodKey)=>void;onRefresh:()=>void;compact?:boolean}) {
  const [measure,setMeasure]=useState<"activities"|"estimatedLifetimeTonnesCo2e">("activities");
  const [postcode,setPostcode]=useState("");
  const {report,loading,error}=state;
  const maximum=Math.max(1,...(report?.activities.map(row=>row[measure]??0)??[]));
  const selected=report?.postcodes.find(row=>row.postcode===postcode);
  return <section className={styles.wrapper} aria-label="Victorian community upgrade impact">
    <div className={styles.hero}>
      <div className={styles.intro}><span className={styles.eyebrow}><CouncilIcon name="leaf" size={16}/>Victorian Energy Upgrades</span><h2>Local upgrades.<br/>A measurable difference.</h2><p>Approved energy upgrades across your community, with their estimated lifetime emissions benefit.</p><div className={styles.controls}><label>Upgrade activity period<select aria-label="Public upgrade activity period" value={period} onChange={event=>{const value=event.target.value;if(value==="quarter"||value==="year"||value==="all")onPeriodChange(value);}}><option value="quarter">This quarter</option><option value="year">This year</option><option value="all">All published history</option></select></label><button type="button" onClick={onRefresh} disabled={loading} aria-label="Check public upgrade data"><CouncilIcon name="refresh" size={17}/></button></div></div>
      <div className={styles.figures}><div><span>Estimated lifetime emissions avoided</span><strong>{report?councilNumber(report.totals.estimatedLifetimeTonnesCo2e):loading?"Loading...":"Unavailable"}</strong><small>tonnes CO₂-e over upgrade lifetimes</small></div><div className={styles.secondaryFigure}><span>Approved upgrade activities</span><strong>{report?councilNumber(report.totals.activities):loading?"Loading...":"Unavailable"}</strong><small>Recorded in your selected postcodes</small></div></div>
    </div>
    {error&&<p className={workspace.error} role="alert">{error} <button type="button" className={workspace.textButton} onClick={onRefresh}>Try again</button></p>}
    {report&&<>
      <div className={styles.source}><span>Official public register</span><span>Source refreshed {councilDate(report.source.refreshedAt)}</span><span>{report.period.label}{report.period.startDate&&report.period.endDate?` · ${councilDate(report.period.startDate)} to ${councilDate(report.period.endDate)}`:""}</span><span>Installer details unavailable</span></div>
      <p className={styles.note}>Estimated lifetime benefit under the scheme methodology, not measured annual emissions. Community-wide activity includes work outside TLink and is not evidence of council attribution.</p>
      {(report.source.stale||report.source.refreshFailed)&&<p className={workspace.notice}>Showing a dated, verified snapshot. {report.source.refreshFailed?"The latest source check was unsuccessful.":"The saved publication may have newer activity."} Source and activity dates above describe the available coverage.</p>}
      {!compact&&<>
        <div className={styles.columns}><CouncilPanel title="What is changing in your community" subtitle="Approved activities in the public register"><div className={styles.tabs}><button type="button" aria-pressed={measure==="activities"} onClick={()=>setMeasure("activities")}>Upgrade activities</button><button type="button" aria-pressed={measure==="estimatedLifetimeTonnesCo2e"} onClick={()=>setMeasure("estimatedLifetimeTonnesCo2e")}>Lifetime emissions benefit</button></div><div className={styles.bars}>{[...report.activities].sort((a,b)=>(b[measure]??-1)-(a[measure]??-1)).map(row=><div key={row.activity}><span>{row.activity}</span><strong>{councilNumber(row[measure])}{measure==="estimatedLifetimeTonnesCo2e"?" t":""}</strong><i><b style={{width:`${(row[measure]??0)/maximum*100}%`}}/></i></div>)}</div></CouncilPanel>
        <CouncilPanel title="Explore your postcodes" subtitle="Select an area to inspect its contribution"><div className={styles.postcodes}>{report.postcodes.map(row=><button type="button" key={row.postcode} aria-pressed={postcode===row.postcode} onClick={()=>setPostcode(row.postcode)}><span>{row.postcode}</span><strong>{councilNumber(row.activities)}</strong><small>approved activities</small></button>)}</div>{selected&&<div className={styles.detail}><strong>{selected.postcode}</strong><p>{councilNumber(selected.estimatedLifetimeTonnesCo2e)} tonnes of estimated lifetime CO₂-e benefit across {councilNumber(selected.activities)} approved activities.</p></div>}<p className={styles.note}>Postcodes can cross council boundaries. This source does not identify the installing business, so local delivery is shown only where TLink has supporting business records.</p></CouncilPanel></div>
        <CouncilPanel title="Ready for your next council report" subtitle="Export the exact scope, values and source evidence" action={<button type="button" className={workspace.secondaryButton} onClick={()=>downloadVeuReport(report)}><CouncilIcon name="download" size={16}/>Export upgrade impact</button>}><details className={styles.method}><summary>How this impact is calculated</summary><ul>{report.notes.map(note=><li key={note}>{note}</li>)}</ul><p>Technical scheme quantity: {councilNumber(report.totals.reportedVeecEquivalents)} reported VEEC equivalents. Approved activity quantities are not proof of registered certificate issuance.</p><a href={report.source.url} target="_blank" rel="noreferrer">Open the official public register <CouncilIcon name="external" size={14}/></a></details></CouncilPanel>
      </>}
    </>}
  </section>;
}
export function downloadVeuReport(report:CouncilVeuReport){
  const cell=(value:unknown)=>`"${String(value??"Not available").replace(/^[=+@-]/,"'$&").replaceAll('"','""')}"`;
  const rows:unknown[][]=[["TLink Council | Community upgrade impact"],["Council",report.scope.name],["Postcodes",report.scope.postcodes.join(" ")],["Activity period",report.period.label,report.period.startDate,report.period.endDate],["Source refreshed",report.source.refreshedAt],["Source checked",report.source.checkedAt],["Source",report.source.url],["Basis","Approved activities; estimated lifetime tonnes CO2-e, not annual measured emissions; installer details unavailable"],["Dimension","Area or activity","Approved activities","Estimated lifetime tonnes CO2-e"],["Total","All selected postcodes",report.totals.activities,report.totals.estimatedLifetimeTonnesCo2e],...report.postcodes.map(row=>["Postcode",row.postcode,row.activities,row.estimatedLifetimeTonnesCo2e]),...report.activities.map(row=>["Activity",row.activity,row.activities,row.estimatedLifetimeTonnesCo2e]),...report.notes.map(note=>["Method",note]),...Object.entries(report.provenance).map(([key,value])=>["Evidence hash",key,value])];
  const url=URL.createObjectURL(new Blob(["\uFEFF"+rows.map(row=>row.map(cell).join(",")).join("\r\n")],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`council-upgrade-impact-${report.period.key}-${report.source.refreshedAt.slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
