import type { MetadataRoute } from "next";
import { PUBLIC_SITE } from "@/lib/public-site";

// This is the canonical post-cutover inventory. The candidate host deliberately
// emits apex URLs so the same sitemap can be submitted without changing every
// entry during the DNS move.
const routes = [
  "",
  "/services",
  "/offers",
  "/services/smoke-alarm-blind-safety",
  "/services/gas-safety-check",
  "/services/electrical-safety-check",
  "/services/onsite-energy-assessment",
  "/assessments",
  "/basix-nsw",
  "/book-an-assessment",
  "/blower-door-thermal-imaging",
  "/commercial-and-industrial-assessments",
  "/communities-schools",
  "/faq",
  "/home-energy-rating-for-existing-homes",
  "/minimum-rental-standards",
  "/nathers-for-new-homes",
  "/nathers-whole-of-home",
  "/plan",
  "/wattzun",
  "/calculator",
  "/compare",
  "/gas-compare",
  "/wholesale-electricity",
  "/guides",
  "/guides/products",
  "/guides/products/solar",
  "/guides/products/inverters",
  "/guides/products/batteries",
  "/guides/products/hot-water",
  "/guides/products/air-conditioning",
  "/guides/certificate-prices",
  "/guides/home-energy-upgrades",
  "/guides/prepare-for-home-energy-assessment",
  "/guides/free-home-energy-assessments",
  "/guides/home-energy-assessment-myths",
  "/guides/ncc-nathers-basix",
  "/guides/green-building-certifications-australia",
  "/guides/solar",
  "/guides/batteries",
  "/guides/heating",
  "/guides/heat-pumps",
  "/guides/hot-water",
  "/guides/cooking",
  "/guides/ev-charging",
  "/guides/insulation-draught-proofing",
  "/guides/project-preparation",
  "/rebates",
  "/rental-assessment/request",
  "/home-energy-rating-vs-nathers-vs-scorecard",
  "/residential-efficiency-scorecard",
  "/case-studies",
  "/platform",
  "/privacy",
  "/team",
  "/trusted-suppliers",
  "/direct-trade",
  "/direct-trade/for-trades",
  "/direct-trade/for-councils",
  "/direct-trade/integrations",
  "/direct-trade/standards",
] as const;

const lastModifiedByRoute = new Map<(typeof routes)[number], string>([
  ["/services", "2026-09-14"],
  ["/minimum-rental-standards", "2026-09-14"],
  ["/offers", "2026-09-14"],
  ["/services/smoke-alarm-blind-safety", "2026-09-14"],
  ["/services/gas-safety-check", "2026-09-14"],
  ["/services/electrical-safety-check", "2026-09-14"],
  ["/services/onsite-energy-assessment", "2026-09-14"],
  ["", "2026-10-09"],
  ["/guides", "2026-10-10"],
  ["/guides/products", "2026-10-10"],
  ["/guides/products/solar", "2026-10-10"],
  ["/guides/products/inverters", "2026-10-10"],
  ["/guides/products/batteries", "2026-10-10"],
  ["/guides/products/hot-water", "2026-10-10"],
  ["/guides/products/air-conditioning", "2026-10-10"],
  ["/guides/solar", "2026-10-10"],
  ["/guides/batteries", "2026-10-10"],
  ["/guides/heating", "2026-10-10"],
  ["/guides/hot-water", "2026-10-10"],
  ["/plan", "2026-10-10"],
  ["/case-studies", "2026-10-09"],
  ["/platform", "2026-10-09"],
  ["/faq", "2026-10-09"],
  ["/direct-trade/for-trades", "2026-10-10"],
  ["/direct-trade/for-councils", "2026-10-09"],
  ["/direct-trade/integrations", "2026-10-09"],
  ["/wholesale-electricity", "2026-09-04"],
  ["/assessments", "2026-10-09"],
  ["/book-an-assessment", "2026-09-14"],
  ["/blower-door-thermal-imaging", "2026-09-04"],
  ["/guides/home-energy-upgrades", "2026-09-04"],
  ["/home-energy-rating-for-existing-homes", "2026-10-09"],
  ["/nathers-for-new-homes", "2026-10-09"],
  ["/compare", "2026-10-10"],
  ["/gas-compare", "2026-10-10"],
  ["/guides/prepare-for-home-energy-assessment", "2026-09-03"],
  ["/guides/free-home-energy-assessments", "2026-09-03"],
  ["/guides/ncc-nathers-basix", "2026-09-03"],
]);

export default function sitemap(): MetadataRoute.Sitemap {
  return routes.map((route) => {
    const lastModified = lastModifiedByRoute.get(route);
    return {
      url: new URL(route || "/", `${PUBLIC_SITE.apexUrl}/`).toString(),
      ...(lastModified ? { lastModified } : {}),
    };
  });
}
