/* eslint-disable @next/next/no-html-link-for-pages */
import { SiteFooter, SiteHeader } from "./ComparatorChrome";

export function DirectTradeProjectBrief() {
  return <main id="main-content" className="wrap direct-trade-request-page customer-project-entry-page">
    <SiteHeader active="direct-trade-request" />
    <header className="direct-trade-request-hero customer-project-entry-hero"><div><span>Private household projects</span><h1>Ask for upgrade options without handing your details to sales teams</h1><p>Build a guided home project inside a free customer account. Your name, email, phone, street address, exact postcode and private notes remain hidden through matching and quote review.</p><div className="trade-account-hero-links"><a className="btn" href="/account/projects/new">Create a free private project</a><a className="direct-trade-hero-link" href="/account">Open my account</a></div></div><aside><strong>No public lead form</strong><p>Household enquiries live inside the protected customer dashboard. A customer can later choose one named business and release contact details to it.</p><span className="trade-free-access-badge">Always free for households</span></aside></header>
    <section className="customer-project-entry-flow" aria-labelledby="private-project-flow-title"><div className="guide-section-heading"><span>How it works</span><h2 id="private-project-flow-title">From an idea to a customer-controlled connection</h2></div><ol><li><span>01</span><div><h3>Create your private project</h3><p>Save structured property context, goals, equipment, priorities and optional photos or files in your own account.</p></div></li><li><span>02</span><div><h3>Review the installer view</h3><p>See the anonymised property and work scope with contact details withheld during matching. Customer-authored names and notes never enter it. If you attach files, you must confirm that every allocated verified installer can view them for quoting guidance.</p></div></li><li><span>03</span><div><h3>Suitable installers respond</h3><p>Only eligible verified installers allocated to the enquiry can see its matched scope and customer-approved attached files. Wholesalers never receive household leads.</p></div></li><li><span>04</span><div><h3>Choose whether to connect</h3><p>Choose one business to contact. This releases your contact details to that business but does not accept a quote, make a payment or authorise work.</p></div></li></ol></section>
    <section className="customer-project-entry-boundaries"><article><span>Stored privately</span><h2>Your account side</h2><ul><li>Account name and email</li><li>Phone and full service address</li><li>Private project name, budget and notes</li><li>Saved roadmap progress</li></ul></article><article><span>Shared during matching</span><h2>Installer scope</h2><ul><li>State and service-area eligibility</li><li>Controlled property class and work types</li><li>Project stage, timing and priorities</li><li>Every customer-approved photo or supporting document</li></ul></article><article><span>Shared only by you</span><h2>Named-business contact</h2><ul><li>Requires your explicit contact choice</li><li>Names the verified business first</li><li>Releases phone, email and service address only to that match</li><li>Leaves every other installer anonymised</li></ul></article></section>
    <section className="customer-project-entry-actions"><div><span>Plan first, enquire when ready</span><h2>Your roadmap remains useful even if you never request a quote</h2><p>Create multiple projects, mark decisions complete and return later from any device. Submitting for installer responses is always optional.</p></div><div><a className="btn" href="/account/projects/new">Start my project</a><a className="btn ghost" href="/plan">Use the planner without an account</a><a className="btn ghost" href="/direct-trade/standards">Read the marketplace standards</a></div></section>
    <SiteFooter>Customer projects and roadmaps are free. Structured installer options remain indicative until the full property, approvals, products and complete installed scope are confirmed in writing.</SiteFooter>
  </main>;
}
