/* eslint-disable @next/next/no-html-link-for-pages */
import { SiteFooter, SiteHeader } from "./ComparatorChrome";

export function DirectTradeProjectBrief() {
  return <main id="main-content" className="wrap direct-trade-request-page customer-project-entry-page">
    <SiteHeader active="direct-trade-request" />
    <header className="direct-trade-request-hero customer-project-entry-hero"><div><span>Private household projects</span><h1>Ask for upgrade options without handing your details to sales teams</h1><p>Build a guided home project inside a free customer account. The platform creates a controlled installer scope while your name, email, phone, street address, exact postcode and private notes remain hidden.</p><div className="trade-account-hero-links"><a className="btn" href="/account/projects/new">Create a free private project</a><a className="direct-trade-hero-link" href="/account">Open my account</a></div></div><aside><strong>No public lead form</strong><p>Household enquiries now live inside the protected customer dashboard instead of being emailed or distributed as contact records.</p><span className="trade-trial-badge">Always free for households</span></aside></header>
    <section className="customer-project-entry-flow" aria-labelledby="private-project-flow-title"><div className="guide-section-heading"><span>How it works</span><h2 id="private-project-flow-title">From an idea to comparable options, without direct trade contact</h2></div><ol><li><span>01</span><div><h3>Create your private project</h3><p>Save the home context, goals, equipment, priorities, roadmap and notes in your own account.</p></div></li><li><span>02</span><div><h3>Review the installer view</h3><p>See the anonymised scope before it is submitted. Customer-authored names and notes never enter it.</p></div></li><li><span>03</span><div><h3>Suitable installers respond</h3><p>Only eligible paid installers can see a matched scope. Wholesalers never receive household leads.</p></div></li><li><span>04</span><div><h3>Compare structured options</h3><p>Review product, labour, timing and warranty fields inside your dashboard. No direct messages or contact details are exchanged.</p></div></li></ol></section>
    <section className="customer-project-entry-boundaries"><article><span>Stored privately</span><h2>Your account side</h2><ul><li>Account name and email</li><li>Exact postcode and home nickname</li><li>Private project name, budget and notes</li><li>Saved roadmap progress</li></ul></article><article><span>Shared safely</span><h2>Installer scope</h2><ul><li>State and service-area eligibility</li><li>Controlled property class and work types</li><li>Project stage, timing and priorities</li><li>Structured quote response fields</li></ul></article><article><span>Never provided</span><h2>Sales contact data</h2><ul><li>No customer phone number</li><li>No customer email address</li><li>No street address or precise distance</li><li>No direct message channel</li></ul></article></section>
    <section className="customer-project-entry-actions"><div><span>Plan first, enquire when ready</span><h2>Your roadmap remains useful even if you never request a quote</h2><p>Create multiple projects, mark decisions complete and return later from any device. Submitting for installer responses is always optional.</p></div><div><a className="btn" href="/account/projects/new">Start my project</a><a className="btn ghost" href="/plan">Use the planner without an account</a><a className="btn ghost" href="/direct-trade/standards">Read the marketplace standards</a></div></section>
    <SiteFooter>Customer projects and roadmaps are free. Structured installer options remain indicative until the full property, approvals, products and complete installed scope are confirmed in writing.</SiteFooter>
  </main>;
}
