import { SiteFooter, SiteHeader } from "./ComparatorChrome";

const preparation = [
  { number: "1", title: "Bring a recent bill", text: "Your postcode, retailer, plan name and energy use help establish a useful comparison." },
  { number: "2", title: "Use the best evidence you have", text: "Electricity meter data gives the strongest time-of-use comparison. Annual or recent-bill usage can still provide an indicative result." },
  { number: "3", title: "Confirm before switching", text: "Check the final rates, eligibility, concessions, fees and contract terms directly with the retailer." },
];

export function GettingStarted() {
  return <main className="wrap start-page">
    <SiteHeader active="start" />
    <header className="start-hero">
      <div className="start-hero-copy"><span className="start-eyebrow">Direct Trade Services</span><h1>Go direct to the licensed trades who do the work</h1><p>We connect households with qualified local installers through an active trade network, with fewer sales layers, itemised quotes and rebate assumptions you can verify. This tool is bringing that service into one clear online journey.</p><div className="start-actions"><a className="btn" href="/direct-trade">Start a project brief</a><a className="btn ghost" href="#compare-energy-plans">Compare energy plans</a></div><aside aria-label="Direct Trade Services principles"><strong>Built to remove avoidable layers</strong><ul><li>Access to a live trade network</li><li>Itemised equipment and labour</li><li>Visible rebate assumptions</li><li>Qualified trades and reputable suppliers</li></ul></aside></div>
      <div className="start-hero-visual" role="img" aria-label="Home energy platform showing solar, a battery, heating and hot water" />
    </header>

    <section className="direct-trade-section" id="direct-trade-model" aria-labelledby="direct-trade-title"><div className="start-heading"><span>Why direct to trade</span><h2 id="direct-trade-title">Fewer layers. A clearer path from assessment to installation.</h2><p>Traditional upgrade channels can include sales, referral and administration businesses before a licensed contractor performs the work. Those layers can add cost without changing the equipment wholesaler or the trade responsible for the installation. Direct Trade Services shortens that path while keeping consumer protections and compliance checks intact.</p></div><div className="direct-trade-grid"><article><span>01</span><h3>Assess the need first</h3><p>Use household evidence to understand the problem, compare options and make material assumptions visible before requesting installation quotes.</p></article><article><span>02</span><h3>Connect with verified trades</h3><p>Participating installers are reviewed for current trade credentials, insurance, service area and scheme-specific approval where the work requires it.</p></article><article><span>03</span><h3>See where the money goes</h3><p>Quotes should separate equipment, labour, certificates or rebates, optional extras, warranty terms and any condition that could change the final price.</p></article></div><div className="direct-trade-economics"><article><span>For households</span><h3>A quote you can interrogate</h3><p>Direct contact with the participating trade, a defined scope and official program links for any rebate or certificate claim.</p></article><article><span>For installers</span><h3>Qualified opportunities, not a sales hierarchy</h3><p>Verified members receive relevant household opportunities and a profile that explains their credentials, capabilities and service area.</p></article><article><span>For wholesalers</span><h3>Quality products into customers’ homes</h3><p>A place for reputable suppliers to connect proven products with qualified trades and suitable households, backed by clear product, warranty and support evidence.</p></article><article><span>How the platform is funded</span><h3>A disclosed installer subscription</h3><p>Participating installers fund the service through a current subscription. It is not a margin added to household equipment and it is not a highest-bidder lead auction.</p></article></div></section>

    <section className="start-section" id="compare-energy-plans" aria-labelledby="choose-path-title"><div className="start-heading"><span>Available now</span><h2 id="choose-path-title">Start with your household evidence</h2><p>Electricity and gas use different data and pricing methods, so each has its own comparison journey.</p></div><div className="start-path-grid">
      <article className="start-path-card"><span className="start-path-tag">Electricity</span><h3>Compare electricity plans</h3><p>Use a postcode and annual usage, or add locally processed NEM12 meter data for a stronger time-of-use result.</p><ul><li>Residential and small-business options</li><li>Solar, battery and controlled-load scenarios</li><li>Charge-level calculation evidence</li></ul><a href="/compare">Start electricity comparison</a></article>
      <article className="start-path-card"><span className="start-path-tag">Mains gas</span><h3>Compare gas plans</h3><p>Use a full year of MJ or one recent bill. The tool accounts for seasonal heating use and published gas tariff blocks.</p><ul><li>Mains gas plans only, not LPG</li><li>Distributor confirmation where required</li><li>Concession and condition disclosures</li></ul><a href="/gas-compare">Start gas comparison</a></article>
    </div></section>

    <section className="start-section start-prepare" aria-labelledby="prepare-title"><div className="start-heading"><span>Before you begin</span><h2 id="prepare-title">Three steps to a reliable result</h2></div><div className="start-step-grid">{preparation.map((item) => <article key={item.number}><span>{item.number}</span><div><h3>{item.title}</h3><p>{item.text}</p></div></article>)}</div></section>

    <section className="start-privacy"><div><span>Privacy first</span><h2>Your meter file stays on your device</h2><p>Electricity interval files are processed locally in your browser. Meter identifiers, interval records and filenames are not included in saved comparison links or enquiry data.</p></div><a href="/compare">Use meter data safely</a></section>

    <section className="start-section" aria-labelledby="upgrade-guides-title"><div className="start-heading"><span>Plan an upgrade</span><h2 id="upgrade-guides-title">Home energy guides</h2><p>Understand the evidence, quote details, installer checks and assumptions before choosing equipment.</p></div><div className="start-guide-grid"><a href="/guides/solar"><span>Rooftop solar</span><strong>Match generation to your home</strong><small>Size, self-consumption, exports, quotes and installers</small></a><a href="/guides/batteries"><span>Home batteries</span><strong>Test storage against your load</strong><small>Capacity, power, backup, warranties and federal support</small></a><a href="/guides/heating"><span>Heating and cooling</span><strong>Reduce demand, then choose the system</strong><small>Climate-zone ratings, sizing, noise, comfort and quotes</small></a><a href="/guides/hot-water"><span>Hot water</span><strong>Match capacity and timing to your household</strong><small>Heat pumps, solar, tariffs, noise, backup and incentives</small></a><a className="start-guide-wide" href="/guides/insulation-draught-proofing"><span>Building fabric</span><strong>Control heat flow and unwanted draughts</strong><small>Insulation, air leakage, ventilation, moisture, safety and quote scope</small></a></div></section>
    <section className="start-support"><div><span>Check support</span><h2>Rebates depend on where you live</h2><p>Use the rebates and assistance hub to choose your state or territory, separate federal certificates from local programs and confirm the official rules.</p></div><a href="/rebates">Find rebates and assistance</a></section>
    <section className="direct-trade-installer" aria-labelledby="installer-title"><div><span>For licensed installers</span><h2 id="installer-title">Built for the trades who already do the work</h2><p>Direct Trade members can present verified credentials, service areas and upgrade capabilities, then receive relevant opportunities without funding another sales hierarchy.</p><ul><li>Current licence or registration for every service offered</li><li>Scheme-specific accreditation or approval where required</li><li>Insurance, written scope, warranties and a complaint process</li><li>Clear subscription terms with no promise of guaranteed lead volume</li></ul></div><aside><strong>Membership is not a government accreditation</strong><p>“Direct Trade Specialist” describes verified membership in the Australian Energy Assessments program. It does not replace a trade licence, government accreditation or scheme-specific installer approval.</p><span>Membership is reviewed directly.</span></aside></section>
    <section className="start-next"><h2>See the method in practice</h2><p>Our <a href="/case-studies">worked examples</a> explain why electricity timing, solar self-use and seasonal gas evidence can change the decision, without presenting invented customer claims.</p></section>
    <SiteFooter>Estimates are indicative. Confirm current prices, eligibility, concessions and conditions with the retailer, official program administrator or installer before committing.</SiteFooter>
  </main>;
}
