"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

type Line = { id: string; description: string; quantityMilli: number; unitPriceCents: number; subtotalCents: number; taxCents: number; totalCents: number; sectionHeading: string };
type Choice = { id: string; kind: "package" | "addon" | "choose_one"; groupKey: string; name: string; summary: string; recommended: boolean; subtotalCents: number; taxCents: number; totalCents: number; items: Line[] };
type Question = { id: string; question: string; answer: string; status: string; askedAt: string; answeredAt: string };
type Quote = { linkId: string; quoteVersionId: string; quoteNumber: string; versionNumber: number; workNumber: string; workTitle: string; customerName: string; customerNumber: string; siteLabel: string; siteSummary: string;
  business: { name: string; email: string; phone: string; abn: string }; subtotalCents: number; taxCents: number; totalCents: number; terms: string; validUntil: string; issuedAt: string; consentStatement: string; expiresAt: string; items: Line[]; choices: Choice[]; questions: Question[] };
type Result = { ok?: boolean; quote?: Quote; decision?: string; error?: string };
const money = (cents: number) => new Intl.NumberFormat("en-AU", { style: "currency", currency: "AUD" }).format(cents / 100);

function QuoteLines({ lines }: { lines: Line[] }) {
  const sections = [...new Set(lines.map((line) => line.sectionHeading || "Included work"))];
  return <div className="quote-link-sections">{sections.map((section) => <section key={section}><h4>{section}</h4>{lines.filter((line) => (line.sectionHeading || "Included work") === section).map((line) => <div key={line.id}><span><b>{line.description}</b><small>{line.quantityMilli / 1000} × {money(line.unitPriceCents)}</small></span><strong>{money(line.totalCents)}</strong></div>)}</section>)}</div>;
}

export function QuoteLinkReview({ token }: { token: string }) {
  const [quote, setQuote] = useState<Quote | null>(null); const [selected, setSelected] = useState<string[]>([]); const [signerName, setSignerName] = useState("");
  const [consent, setConsent] = useState(false); const [question, setQuestion] = useState(""); const [busy, setBusy] = useState(""); const [message, setMessage] = useState(""); const [finished, setFinished] = useState("");
  const endpoint = `/api/quote-review/${encodeURIComponent(token)}`;
  const load = useCallback(async () => { const response = await fetch(endpoint, { cache: "no-store" }); const result = await response.json().catch(() => ({})) as Result; if (!response.ok || !result.quote) throw new Error(result.error || "This quote could not be opened."); setQuote(result.quote);
    const required = new Map<string, Choice>(); for (const choice of result.quote.choices.filter((item) => item.kind !== "addon")) { const key = `${choice.kind}:${choice.groupKey}`; const current = required.get(key); if (!current || choice.recommended) required.set(key, choice); } setSelected([...required.values()].map((item) => item.id)); }, [endpoint]);
  useEffect(() => { const frame = window.requestAnimationFrame(() => void load().catch((error) => setMessage(error instanceof Error ? error.message : "This quote could not be opened."))); return () => window.cancelAnimationFrame(frame); }, [load]);

  const selectedChoices = useMemo(() => quote?.choices.filter((choice) => selected.includes(choice.id)) || [], [quote, selected]);
  const totals = useMemo(() => ({ subtotal: (quote?.subtotalCents || 0) + selectedChoices.reduce((sum, choice) => sum + choice.subtotalCents, 0), tax: (quote?.taxCents || 0) + selectedChoices.reduce((sum, choice) => sum + choice.taxCents, 0), total: (quote?.totalCents || 0) + selectedChoices.reduce((sum, choice) => sum + choice.totalCents, 0) }), [quote, selectedChoices]);
  function choose(choice: Choice) { setSelected((current) => choice.kind === "addon" ? current.includes(choice.id) ? current.filter((id) => id !== choice.id) : [...current, choice.id] : [...current.filter((id) => !quote?.choices.some((item) => item.id === id && item.kind === choice.kind && item.groupKey === choice.groupKey)), choice.id]); }
  async function post(body: Record<string, unknown>) { const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json().catch(() => ({})) as Result; if (!response.ok) throw new Error(result.error || "The quote could not be updated."); return result; }
  async function ask() { setBusy("question"); setMessage(""); try { const result = await post({ action: "ask_question", question }); if (result.quote) setQuote(result.quote); setQuestion(""); setMessage("Your question is now in the trade office timeline."); } catch (error) { setMessage(error instanceof Error ? error.message : "Your question could not be sent."); } finally { setBusy(""); } }
  async function decide(decision: "accepted" | "declined") { setBusy(decision); setMessage(""); try { const result = await post({ action: "decide", decision, signerName, consentConfirmed: consent, selectedChoiceIds: selected }); setFinished(result.decision || decision); } catch (error) { setMessage(error instanceof Error ? error.message : "Your decision could not be recorded."); } finally { setBusy(""); } }
  if (finished) return <main className="quote-link-shell"><section className="quote-link-finished"><span>Decision recorded</span><h1>Quote {finished}</h1><p>The trade business now has your signed decision and exact total. This secure link has closed automatically.</p></section></main>;
  if (!quote) return <main className="quote-link-shell"><section className="quote-link-loading"><strong>Opening secure quote</strong>{message && <p role="alert">{message}</p>}</section></main>;
  const groups = [...new Set(quote.choices.filter((choice) => choice.kind !== "addon").map((choice) => `${choice.kind}:${choice.groupKey}`))]; const addons = quote.choices.filter((choice) => choice.kind === "addon");
  return <main className="quote-link-shell"><article className="quote-link-document">
    <header><div><span>Quote from</span><h1>{quote.business.name}</h1><p>{quote.business.phone}{quote.business.email ? ` | ${quote.business.email}` : ""}{quote.business.abn ? ` | ABN ${quote.business.abn}` : ""}</p></div><button type="button" className="quote-print-button" onClick={() => window.print()}>Print or save PDF</button></header>
    <section className="quote-link-summary"><div><span>Quote</span><strong>{quote.quoteNumber} | Version {quote.versionNumber}</strong></div><div><span>Prepared for</span><strong>{quote.customerName}</strong><small>{quote.siteLabel} | {quote.siteSummary}</small></div><div><span>Work</span><strong>{quote.workTitle}</strong><small>{quote.workNumber}</small></div><div><span>Valid until</span><strong>{quote.validUntil || "Contact trade business"}</strong></div></section>
    {quote.items.length > 0 && <section className="quote-link-block"><span>Always included</span><h2>Your base scope</h2><QuoteLines lines={quote.items} /></section>}
    {groups.map((group) => { const choices = quote.choices.filter((choice) => `${choice.kind}:${choice.groupKey}` === group); return <fieldset className="quote-link-choices" key={group}><legend>{choices[0]?.kind === "package" ? "Choose your package" : "Choose one"}</legend><p>One clear selection is required.</p><div>{choices.map((choice) => <label className={`${selected.includes(choice.id) ? "selected" : ""} ${choice.recommended ? "recommended" : ""}`} key={choice.id}><input type="radio" name={group} checked={selected.includes(choice.id)} onChange={() => choose(choice)} /><span>{choice.recommended && <em>Recommended</em>}<b>{choice.name}</b><small>{choice.summary}</small><strong>{money((quote.totalCents || 0) + choice.totalCents)} incl GST before other extras</strong></span><QuoteLines lines={choice.items} /></label>)}</div></fieldset>; })}
    {addons.length > 0 && <fieldset className="quote-link-choices addons"><legend>Optional extras</legend><p>Add only what you want.</p><div>{addons.map((choice) => <label className={selected.includes(choice.id) ? "selected" : ""} key={choice.id}><input type="checkbox" checked={selected.includes(choice.id)} onChange={() => choose(choice)} /><span><b>{choice.name}</b><small>{choice.summary}</small><strong>+ {money(choice.totalCents)}</strong></span><QuoteLines lines={choice.items} /></label>)}</div></fieldset>}
    <section className="quote-link-total" aria-live="polite"><span>Your confirmed total</span><strong>{money(totals.total)}</strong><dl><div><dt>Subtotal</dt><dd>{money(totals.subtotal)}</dd></div><div><dt>GST</dt><dd>{money(totals.tax)}</dd></div></dl><small>Calculated and checked again by the server when you accept.</small></section>
    <section className="quote-link-terms"><span>Recorded terms</span><h2>Scope, exclusions and completion terms</h2><p>{quote.terms}</p></section>
    <section className="quote-link-question"><span>Need one detail clarified?</span><h2>Ask the trade business</h2>{quote.questions.map((item) => <article key={item.id}><strong>Your question</strong><p>{item.question}</p>{item.answer && <><strong>Trade response</strong><p>{item.answer}</p></>}</article>)}<label><span>Your question</span><textarea value={question} maxLength={1000} rows={3} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask about the scope, timing or an option" /></label><button type="button" disabled={busy === "question" || question.trim().length < 5} onClick={() => void ask()}>{busy === "question" ? "Sending..." : "Send question"}</button></section>
    <section className="quote-link-signature"><span>Signed decision</span><h2>Type your name to sign</h2><label><span>Full name</span><input value={signerName} maxLength={160} autoComplete="name" onChange={(event) => setSignerName(event.target.value)} /></label><label className="quote-link-consent"><input type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} /><span>I confirm I am authorised to make this decision and understand it applies to this exact quote version, selected choices, total and recorded terms.</span></label><div><button className="primary" type="button" disabled={Boolean(busy) || signerName.trim().length < 2 || !consent} onClick={() => void decide("accepted")}>{busy === "accepted" ? "Recording..." : `Accept for ${money(totals.total)}`}</button><button type="button" disabled={Boolean(busy) || signerName.trim().length < 2 || !consent} onClick={() => void decide("declined")}>{busy === "declined" ? "Recording..." : "Decline quote"}</button></div></section>
    {message && <p className="quote-link-message" role="status">{message}</p>}
  </article></main>;
}
