"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import type { User } from "firebase/auth";

type Location = { id: string; locationName: string; locationType: string; addressLine1: string; suburb: string; addressState: string; postcode: string; salesEmail: string; contactNumber: string; dispatchNotes: string; serviceStates: string[] };
const states = ["ACT", "NSW", "NT", "QLD", "SA", "TAS", "VIC", "WA"];
export function SupplierLocationManager({ user }: { user: User }) {
  const [locations, setLocations] = useState<Location[]>([]); const [editing, setEditing] = useState<Location | null>(null); const [adding, setAdding] = useState(false); const [status, setStatus] = useState("");
  const request = useCallback(async (init?: RequestInit) => { const token = await user.getIdToken(); const response = await fetch("/api/supplier-locations", { ...init, headers: { ...(init?.body ? { "Content-Type": "application/json" } : {}), Authorization: `Bearer ${token}` }, cache: "no-store" }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.error || "Locations could not be updated."); setLocations(result.locations || []); }, [user]);
  useEffect(() => { const frame = requestAnimationFrame(() => void request().catch((error) => setStatus(error instanceof Error ? error.message : "Locations could not be loaded."))); return () => cancelAnimationFrame(frame); }, [request]);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const serviceStates = states.filter((state) => form.get(`state-${state}`)); setStatus("Saving location..."); try { await request({ method: "POST", body: JSON.stringify({ id: editing?.id || "", locationName: form.get("locationName"), locationType: form.get("locationType"), addressLine1: form.get("addressLine1"), suburb: form.get("suburb"), addressState: form.get("addressState"), postcode: form.get("postcode"), salesEmail: form.get("salesEmail"), contactNumber: form.get("contactNumber"), dispatchNotes: form.get("dispatchNotes"), serviceStates }) }); setEditing(null); setAdding(false); setStatus("Location saved to your installer-facing TLink profile."); } catch (error) { setStatus(error instanceof Error ? error.message : "Location could not be saved."); } }
  return <section className="dashboard-panel supplier-location-manager"><header><div><span>Installer-facing profile</span><h2>Dispatch and warehouse locations</h2><p>Give installers the right sales contact and dispatch details without a phone call.</p></div><button type="button" onClick={() => { setEditing(null); setAdding(true); }}>Add location</button></header>
    <div className="supplier-location-cards">{locations.map((location) => <article key={location.id}><span>{location.locationType.replaceAll("_", " ")}</span><strong>{location.locationName}</strong><p>{location.addressLine1}, {location.suburb} {location.addressState} {location.postcode}</p><small>{location.salesEmail || location.contactNumber || "No sales contact supplied"}</small><div><button type="button" onClick={() => { setEditing(location); setAdding(true); }}>Edit</button><button type="button" onClick={() => void request({ method: "POST", body: JSON.stringify({ action: "archive", id: location.id }) })}>Archive</button></div></article>)}</div>
    {adding && <form className="supplier-location-form" onSubmit={save}><div className="supplier-form-grid"><label><span>Location name</span><input name="locationName" required defaultValue={editing?.locationName} placeholder="Melbourne dispatch" /></label><label><span>Location type</span><select name="locationType" defaultValue={editing?.locationType || "warehouse"}><option value="head_office">Head office</option><option value="warehouse">Warehouse</option><option value="dispatch">Dispatch</option><option value="showroom">Showroom</option></select></label><label><span>Street address</span><input name="addressLine1" required defaultValue={editing?.addressLine1} /></label><label><span>Suburb</span><input name="suburb" required defaultValue={editing?.suburb} /></label><label><span>State</span><select name="addressState" defaultValue={editing?.addressState || "VIC"}>{states.map((state) => <option key={state}>{state}</option>)}</select></label><label><span>Postcode</span><input name="postcode" required inputMode="numeric" pattern="[0-9]{4}" defaultValue={editing?.postcode} /></label><label><span>Sales email</span><input name="salesEmail" type="email" defaultValue={editing?.salesEmail} /></label><label><span>Contact number</span><input name="contactNumber" type="tel" defaultValue={editing?.contactNumber} /></label></div><fieldset><legend>Dispatch coverage</legend>{states.map((state) => <label key={state}><input type="checkbox" name={`state-${state}`} defaultChecked={editing?.serviceStates.includes(state)} /> {state}</label>)}</fieldset><label><span>Useful dispatch notes</span><textarea name="dispatchNotes" defaultValue={editing?.dispatchNotes} placeholder="Cut-off times, pickup instructions or freight notes" /></label><div><button type="submit">Save location</button><button type="button" onClick={() => { setAdding(false); setEditing(null); }}>Cancel</button></div></form>}
    {status && <p className="dashboard-settings-status" role="status">{status}</p>}
  </section>;
}
