"use client";

import type { User } from "firebase/auth";
import { FormEvent, useCallback, useEffect, useId, useState } from "react";
import { SearchableLookup, type SearchableLookupOption } from "./SearchableLookup";

type Template = { id: string; name: string; title: string; serviceCategory: string; priority: string; description: string; taskTitles: string[] };
type Customer = { id: string; customerNumber: string; displayName: string; phone: string; suburb: string; postcode: string };
type Site = { id: string; siteLabel: string; addressLine1: string; suburb: string; addressState: string; postcode: string; isPrimary: boolean };
type AddressSuggestion = { id: string; label: string; addressLine1: string; addressLine2: string; suburb: string; addressState: string; postcode: string };

const serviceLabels: Record<string, string> = { assessment: "Energy assessment", solar: "Rooftop solar", battery: "Home batteries", "heating-cooling": "Heating and cooling", "hot-water": "Hot water", "insulation-draughts": "Insulation and draught control", "ev-charging": "EV charging", electrical: "Electrical services", plumbing: "Plumbing services", "mounting-hardware": "Mounting and hardware", controls: "Energy controls", other: "Other work" };
const genericTitles = ["Inspection or quote", "Service or repair", "Installation", "Maintenance", "Emergency or breakdown", "Compliance check", "Return visit"];
const categoryTitles: Record<string, string[]> = { plumbing: ["Leak repair", "Hot water service", "Fixture installation"], electrical: ["Electrical fault repair", "Switchboard inspection", "Electrical installation"], "heating-cooling": ["Heating and cooling service", "Split system installation"], "hot-water": ["Hot water system service", "Heat pump hot water installation"], solar: ["Solar inspection", "Solar installation"], battery: ["Battery assessment", "Battery installation"], assessment: ["Energy assessment", "Site inspection and quote"] };
const buildingTypes = [["house_townhouse", "House or townhouse"], ["apartment_unit", "Apartment or unit"], ["commercial_office", "Commercial or office"], ["retail_hospitality", "Retail or hospitality"], ["industrial_warehouse", "Industrial or warehouse"], ["institutional_community_health", "Institutional, community or health"], ["other", "Other"], ["not_sure", "Not sure"]];

function AddressFields({ user }: { user: User }) {
  const id = useId();
  const [value, setValue] = useState({ addressLine1: "", addressLine2: "", suburb: "", addressState: "", postcode: "" });
  const [suggestions, setSuggestions] = useState<AddressSuggestion[]>([]); const [activeIndex, setActiveIndex] = useState(0); const [configured, setConfigured] = useState<boolean | null>(null); const [providerMessage, setProviderMessage] = useState("");
  useEffect(() => {
    if (value.addressLine1.trim().length < 3) return;
    let active = true; const timer = window.setTimeout(() => { void user.getIdToken().then((token) => fetch(`/api/trade-address-suggestions?query=${encodeURIComponent(value.addressLine1)}`, { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" })).then((response) => response.json()).then((result: { configured?: boolean; suggestions?: AddressSuggestion[]; error?: string }) => { if (active) { setConfigured(Boolean(result.configured)); setProviderMessage(result.error || ""); setSuggestions(result.suggestions || []); setActiveIndex(0); } }).catch(() => { if (active) { setProviderMessage("Address suggestions are unavailable. Enter the address manually."); setSuggestions([]); } }); }, 220);
    return () => { active = false; window.clearTimeout(timer); };
  }, [user, value.addressLine1]);
  function choose(item: AddressSuggestion) { setValue({ addressLine1: item.addressLine1, addressLine2: item.addressLine2, suburb: item.suburb, addressState: item.addressState, postcode: item.postcode }); setSuggestions([]); }
  return <div className="crm-address-fields wide"><label className="wide"><span>Street address</span><input name="addressLine1" required maxLength={140} autoComplete="off" value={value.addressLine1} placeholder="Start typing or enter manually" role="combobox" aria-autocomplete="list" aria-expanded={suggestions.length > 0} aria-controls={`${id}-addresses`} aria-activedescendant={suggestions[activeIndex] ? `${id}-address-${activeIndex}` : undefined} onChange={(event) => { const next = event.target.value; setValue((current) => ({ ...current, addressLine1: next })); setProviderMessage(""); if (next.trim().length < 3) setSuggestions([]); }} onKeyDown={(event) => { if (event.key === "Escape") setSuggestions([]); if (!suggestions.length) return; if (event.key === "ArrowDown") { event.preventDefault(); setActiveIndex((current) => Math.min(current + 1, suggestions.length - 1)); } if (event.key === "ArrowUp") { event.preventDefault(); setActiveIndex((current) => Math.max(current - 1, 0)); } if (event.key === "Enter") { event.preventDefault(); choose(suggestions[activeIndex]); } }} />{suggestions.length > 0 && <div id={`${id}-addresses`} className="crm-address-options" role="listbox">{suggestions.map((item, index) => <button type="button" role="option" aria-selected={activeIndex === index} id={`${id}-address-${index}`} key={item.id} onMouseDown={(event) => event.preventDefault()} onClick={() => choose(item)}>{item.label}</button>)}</div>}<small>{providerMessage || (configured === false ? "Address suggestions need an approved provider and credential. Enter the address manually." : "Choose a suggestion when available or enter the address manually.")}</small></label><label className="wide"><span>Unit, level or building, optional</span><input name="addressLine2" maxLength={140} value={value.addressLine2} onChange={(event) => setValue((current) => ({ ...current, addressLine2: event.target.value }))} /></label><label><span>Suburb</span><input name="suburb" required maxLength={80} value={value.suburb} onChange={(event) => setValue((current) => ({ ...current, suburb: event.target.value }))} /></label><label><span>State</span><select name="addressState" required value={value.addressState} onChange={(event) => setValue((current) => ({ ...current, addressState: event.target.value }))}><option value="">Select state</option>{["ACT", "NSW", "NT", "QLD", "SA", "TAS", "VIC", "WA"].map((state) => <option key={state}>{state}</option>)}</select></label><label><span>Postcode</span><input name="postcode" required inputMode="numeric" maxLength={4} pattern="[0-9]{4}" value={value.postcode} onChange={(event) => setValue((current) => ({ ...current, postcode: event.target.value.replace(/\D/g, "").slice(0, 4) }))} /></label></div>;
}

export function TradeNewJobForm({ user, templates, busy, onSubmit }: { user: User; templates: Template[]; busy: boolean; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) {
  const titleListId = useId(); const [templateId, setTemplateId] = useState(""); const template = templates.find((item) => item.id === templateId);
  const [customerMode, setCustomerMode] = useState<"existing" | "new">("existing"); const [customerId, setCustomerId] = useState(""); const [customerType, setCustomerType] = useState("residential");
  const [sites, setSites] = useState<Site[]>([]); const [serviceSiteId, setServiceSiteId] = useState(""); const [newSite, setNewSite] = useState(false);
  const [serviceCategory, setServiceCategory] = useState("assessment"); const [title, setTitle] = useState(""); const [priority, setPriority] = useState("standard");
  const loadCustomers = useCallback(async (query: string, selected: string): Promise<SearchableLookupOption[]> => {
    const token = await user.getIdToken();
    if (selected && !query) { const response = await fetch(`/api/trade-crm?mode=detail&resource=customer&id=${encodeURIComponent(selected)}`, { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" }); const result = await response.json() as { customer?: Customer }; const customer = result.customer; return customer ? [{ id: customer.id, label: customer.displayName, secondary: [customer.customerNumber, customer.phone, customer.suburb, customer.postcode].filter(Boolean).join(" | ") }] : []; }
    const response = await fetch(`/api/trade-crm?${new URLSearchParams({ mode: "index", resource: "customers", search: query, pageSize: "25", sort: "name-asc", total: "0" })}`, { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" }); const result = await response.json() as { items?: Customer[] };
    return (result.items || []).map((customer) => ({ id: customer.id, label: customer.displayName, secondary: [customer.customerNumber, customer.phone, customer.suburb, customer.postcode].filter(Boolean).join(" | ") }));
  }, [user]);
  useEffect(() => { if (!customerId) return; let active = true; void user.getIdToken().then((token) => fetch(`/api/trade-crm?mode=detail&resource=customer&id=${encodeURIComponent(customerId)}`, { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" })).then((response) => response.json()).then((result: { sites?: Site[] }) => { if (active) { const next = result.sites || []; setSites(next); setServiceSiteId(next.find((site) => site.isPrimary)?.id || next[0]?.id || ""); setNewSite(!next.length); } }); return () => { active = false; }; }, [customerId, user]);
  function selectCustomer(id: string) { setCustomerId(id); if (!id) { setSites([]); setServiceSiteId(""); setNewSite(false); } }
  const presets = [...(categoryTitles[serviceCategory] || []), ...genericTitles];
  return <form className="crm-form crm-new-job" onSubmit={onSubmit}><div className="crm-system-id-note"><span>Job ID</span><strong>Assigned automatically</strong><small>The next number follows your business sequence, such as JOB-000124.</small></div>{templates.length > 0 && <label className="crm-template-picker"><span>Start from a template, optional</span><select name="templateId" value={templateId} onChange={(event) => { const id = event.target.value; const selected = templates.find((item) => item.id === id); setTemplateId(id); if (selected) { setServiceCategory(selected.serviceCategory); setTitle(selected.title); setPriority(selected.priority); } }}><option value="">Blank job</option>{templates.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><small>{template ? `${template.taskTitles.length} checklist items will be added automatically.` : "Templates keep common scopes and checklists consistent."}</small></label>}
    <fieldset className="crm-customer-lookup"><legend>Your customer</legend><input type="hidden" name="customerMode" value={customerMode} /><input type="hidden" name="crmCustomerId" value={customerId} />{customerMode === "existing" ? <><SearchableLookup label="Find and select a customer" value={customerId} placeholder="Name, number, phone, suburb or postcode" required load={loadCustomers} onChange={selectCustomer} /><button type="button" className="crm-text-action" onClick={() => { setCustomerMode("new"); selectCustomer(""); }}>Create new customer</button></> : <><div className="crm-inline-heading"><strong>New customer</strong><button type="button" onClick={() => setCustomerMode("existing")}>Choose existing instead</button></div><div className="crm-form-grid"><label><span>Customer type</span><select name="customerType" value={customerType} onChange={(event) => setCustomerType(event.target.value)}><option value="residential">Residential</option><option value="business">Business</option></select></label>{customerType === "business" ? <label><span>Business name</span><input name="businessName" required maxLength={140} /></label> : <><label><span>First name</span><input name="firstName" required maxLength={80} /></label><label><span>Last name</span><input name="lastName" maxLength={80} /></label></>}<label><span>Phone, optional</span><input type="tel" name="phone" maxLength={40} /></label><label><span>Email, optional</span><input type="email" name="email" maxLength={180} /></label></div></>}<small>AEA protected leads use their authorised workflow and cannot become direct customer records here.</small></fieldset>
    {(customerMode === "new" || customerId) && <fieldset className="crm-service-site"><legend>Job address</legend><input type="hidden" name="serviceSiteMode" value={customerMode === "new" || newSite ? "new" : "existing"} /><input type="hidden" name="serviceSiteId" value={newSite ? "" : serviceSiteId} />{customerMode === "existing" && customerId && !newSite && sites.length > 0 && <label><span>Existing service site</span><select value={serviceSiteId} onChange={(event) => setServiceSiteId(event.target.value)}>{sites.map((site) => <option key={site.id} value={site.id}>{site.siteLabel} | {[site.addressLine1, site.suburb, site.addressState, site.postcode].filter(Boolean).join(", ")}</option>)}</select></label>}{customerMode === "existing" && customerId && <button type="button" className="crm-text-action" onClick={() => setNewSite((value) => !value)}>{newSite ? "Use an existing service site" : "Add a new service site"}</button>}{(customerMode === "new" || newSite) && <div className="crm-form-grid"><label><span>Site name</span><input name="siteLabel" maxLength={100} defaultValue={customerMode === "new" ? "Primary site" : "New service site"} /></label><AddressFields user={user} /></div>}</fieldset>}
    <div className="crm-form-grid"><label className="wide"><span>Job title</span><input name="title" required maxLength={160} list={titleListId} value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Choose a common title or type your own" /><datalist id={titleListId}>{presets.map((item) => <option key={item} value={item} />)}</datalist><small>You can always type a custom title.</small></label><label><span>Work type</span><select name="serviceCategory" value={serviceCategory} onChange={(event) => setServiceCategory(event.target.value)}>{Object.entries(serviceLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label><span>Building type</span><select name="buildingType" defaultValue="not_sure">{buildingTypes.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label><span>Priority</span><select name="priority" value={priority} onChange={(event) => setPriority(event.target.value)}><option value="standard">Standard</option><option value="low">Low</option><option value="high">High</option><option value="urgent">Urgent</option></select></label></div>{template?.description && <input type="hidden" name="description" value={template.description} />}<button className="btn" disabled={busy}>{busy ? "Creating customer, site and job..." : "Create job"}</button></form>;
}
