"use client";

import { useCallback, useEffect, useState } from "react";
import type { User } from "firebase/auth";

type Data = { handoff: boolean; plan: null | { status: string; commercialReference: string; acceptedTotalCents: number; budgetCostCents: number; budgetMarginCents: number; depositRequirement: string }; phases: Array<{ id: string; title: string; customerDescription: string }>; requirements: Array<{ id: string; phaseId: string; type: string; description: string; status: string; totalCostCents: number }>; readiness: null | { scope: boolean; forms: boolean; people: boolean; materials: boolean; deposit: boolean; ready: boolean; assignedTo: string } };
const money = (cents: number) => new Intl.NumberFormat("en-AU", { style: "currency", currency: "AUD" }).format(cents / 100);

export function TradeJobReadinessPanel({ user, workOrderId, onOpenTeam, onChanged }: { user: User; workOrderId: string; onOpenTeam: () => void; onChanged: () => Promise<void> }) {
  const [data, setData] = useState<Data | null>(null); const [busy, setBusy] = useState(false); const [status, setStatus] = useState("");
  const load = useCallback(async () => { const token = await user.getIdToken(); const response = await fetch(`/api/trade-job-readiness?workOrderId=${encodeURIComponent(workOrderId)}`, { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.error || "Job readiness could not be loaded."); setData(result as Data); }, [user, workOrderId]);
  useEffect(() => { const frame = requestAnimationFrame(() => void load().catch((error) => setStatus(error instanceof Error ? error.message : "Job readiness could not be loaded."))); return () => cancelAnimationFrame(frame); }, [load]);
  async function act(action: string, extra: Record<string, unknown> = {}) { setBusy(true); setStatus("Updating job readiness..."); try { const token = await user.getIdToken(); const response = await fetch("/api/trade-job-readiness", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ action, workOrderId, ...extra }) }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.error || "Job readiness could not be updated."); setData(result as Data); setStatus(action === "ready" ? "Job is ready to schedule and dispatch." : "Job plan updated."); if (action === "ready") await onChanged(); } catch (error) { setStatus(error instanceof Error ? error.message : "Job readiness could not be updated."); } finally { setBusy(false); } }
  if (!data) return <section className="crm-job-readiness empty"><span>Ready-to-run job</span><p>{status || "Checking the accepted scope..."}</p></section>;
  if (!data.handoff) return <section className="crm-job-readiness empty"><span>Next step</span><h4>Accept the quote first</h4><p>The accepted scope becomes the job plan automatically, with no retyping.</p></section>;
  if (!data.plan) return <section className="crm-job-readiness empty"><span>Accepted scope</span><h4>Prepare the job in one click</h4><p>TLink will carry the accepted scope, quoted value and known costs into a practical job checklist.</p><button type="button" disabled={busy} onClick={() => void act("prepare")}>{busy ? "Preparing..." : "Prepare ready-to-run job"}</button>{status && <p role="status">{status}</p>}</section>;
  const checks = [["scope", "Scope", "Accepted work is grouped into clear phases."], ["forms", "Forms", "Required paperwork is attached and confirmed."], ["people", "Technician", data.readiness?.assignedTo ? `Assigned to ${data.readiness.assignedTo}.` : "Assign an active technician."], ["materials", "Materials", "Confirm required products before dispatch."], ["deposit", "Deposit", "Only blocks work when your business requires it."]] as const;
  return <section className="crm-job-readiness"><header><div><span>Ready-to-run job</span><h4>{data.plan.commercialReference}</h4><p>The accepted scope is the source of truth. Confirm only what still needs a human decision.</p></div><strong>{data.plan.status === "ready" ? "Ready" : "Planning"}</strong></header>
    <div className="crm-readiness-summary"><article><span>Accepted value</span><strong>{money(data.plan.acceptedTotalCents)}</strong></article><article><span>Known cost</span><strong>{money(data.plan.budgetCostCents)}</strong></article><article><span>Budget margin</span><strong>{money(data.plan.budgetMarginCents)}</strong></article></div>
    <div className="crm-readiness-checks">{checks.map(([key, label, description]) => { const complete = Boolean(data.readiness?.[key]); return <article key={key} className={complete ? "complete" : "attention"}><i aria-hidden="true">{complete ? "✓" : "!"}</i><div><strong>{label}</strong><span>{description}</span></div>{key === "people" && !complete && <button type="button" onClick={onOpenTeam}>Assign</button>}</article>; })}</div>
    <label className="crm-readiness-deposit"><span>Deposit rule for this job</span><select value={data.plan.depositRequirement} disabled={busy} onChange={(event) => void act("deposit", { requirement: event.target.value })}><option value="optional">Optional, do not block work</option><option value="required">Required before work starts</option><option value="waived">Waived for this job</option></select></label>
    <details className="crm-commercial-scope"><summary>Review phases and requirements</summary>{data.phases.map((phase) => <section key={phase.id}><h5>{phase.title}</h5><p>{phase.customerDescription}</p>{data.requirements.filter((item) => item.phaseId === phase.id).map((item) => <div className="crm-readiness-requirement" key={item.id}><span><strong>{item.description}</strong><small>{item.type}{item.totalCostCents ? ` | ${money(item.totalCostCents)} known cost` : ""}</small></span>{["material", "form"].includes(item.type) ? <select value={item.status} disabled={busy} onChange={(event) => void act("requirement", { requirementId: item.id, status: event.target.value })}><option value="required">Needs confirmation</option><option value="confirmed">Confirmed</option><option value="not_needed">Not needed</option></select> : <b>Included</b>}</div>)}</section>)}</details>
    {data.plan.status !== "ready" && <button className="btn" type="button" disabled={busy || !data.readiness?.ready} onClick={() => void act("ready")}>{data.readiness?.ready ? "Mark ready to schedule" : "Clear remaining items"}</button>}{status && <p className="crm-inline-status" role="status">{status}</p>}
  </section>;
}
