"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { createUserWithEmailAndPassword, GoogleAuthProvider, onAuthStateChanged, sendPasswordResetEmail, signInWithEmailAndPassword, signInWithPopup, signOut, updateProfile, type User } from "firebase/auth";
import { firebaseAuth } from "@/lib/firebase-client";
import { SiteFooter, SiteHeader } from "./ComparatorChrome";
import { TradeFieldWorkPanel } from "./TradeFieldWorkPanel";

type Member = { id: string; displayName: string; role: string; status: string };
type Task = { id: string; title: string; dueAt: string; status: string };
type Job = { id: string; workNumber: string; title: string; serviceCategory: string; siteArea: string; stage: string; priority: string; scheduledStart: string; scheduledEnd: string; assigneeMemberId: string; assigneeLabel: string; protectedJob: boolean; serviceAddress: string; tasks: Task[] };
type Result = { ok?: boolean; accepted?: boolean; access?: { businessName: string; role: string; displayName: string; isOwner: boolean; canDispatch: boolean }; members?: Member[]; jobs?: Job[]; error?: string };

const stages = [["backlog", "Planning"], ["ready", "Ready"], ["scheduled", "Scheduled"], ["in_progress", "On site"], ["blocked", "Waiting"], ["completed", "Complete"], ["cancelled", "Cancelled"]];

export function TradeTeamPortal() {
  const [user, setUser] = useState<User | null>(null);
  const [authReady, setAuthReady] = useState(false);
  const [mode, setMode] = useState<"signin" | "create">("signin");
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState("");
  const [data, setData] = useState<Result>({}); const [loading, setLoading] = useState(false); const [busy, setBusy] = useState(""); const [status, setStatus] = useState("");
  const [selectedJobId, setSelectedJobId] = useState("");

  useEffect(() => onAuthStateChanged(firebaseAuth, (next) => { setUser(next); setAuthReady(true); }), []);
  useEffect(() => {
    if (!user) return; let active = true;
    const frame = window.requestAnimationFrame(() => {
      setLoading(true); const invite = new URLSearchParams(window.location.search).get("invite") || "";
      void (async () => {
        const token = await user.getIdToken();
        let response = invite ? await fetch("/api/trade-team", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ action: "accept_invite", token: invite }) }) : await fetch("/api/trade-team", { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" });
        if (!response.ok && invite) response = await fetch("/api/trade-team", { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" });
        const result = await response.json().catch(() => ({})) as Result;
        if (!response.ok) throw new Error(result.error || "The staff portal could not be opened.");
        if (active) { setData(result); setSelectedJobId((current) => current || result.jobs?.[0]?.id || ""); if (invite) window.history.replaceState({}, "", "/direct-trade/team"); }
      })().catch((error) => active && setStatus(error instanceof Error ? error.message : "The staff portal could not be opened."))
        .finally(() => active && setLoading(false));
    });
    return () => { active = false; window.cancelAnimationFrame(frame); };
  }, [user]);

  async function google() { setBusy("auth"); setStatus("Opening Google sign-in..."); try { const provider = new GoogleAuthProvider(); provider.setCustomParameters({ prompt: "select_account" }); await signInWithPopup(firebaseAuth, provider); } catch { setStatus("Google sign-in could not be completed."); } finally { setBusy(""); } }
  async function emailAuth(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy("auth"); setStatus(mode === "create" ? "Creating your team login..." : "Signing in..."); try { if (mode === "create") { const credential = await createUserWithEmailAndPassword(firebaseAuth, email.trim().toLowerCase(), password); await updateProfile(credential.user, { displayName: name.trim() }); } else await signInWithEmailAndPassword(firebaseAuth, email.trim().toLowerCase(), password); setPassword(""); } catch { setStatus("Check the email and password, then try again."); } finally { setBusy(""); } }
  async function reset() { if (!email.trim()) { setStatus("Enter your email first."); return; } await sendPasswordResetEmail(firebaseAuth, email.trim().toLowerCase()).then(() => setStatus("Password reset instructions sent.")).catch(() => setStatus("Password reset could not be sent.")); }
  async function update(body: Record<string, unknown>, key: string, success: string) { if (!user) return; setBusy(key); try { const token = await user.getIdToken(); const response = await fetch("/api/trade-team", { method: "PATCH", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify(body) }); const result = await response.json().catch(() => ({})) as Result; if (!response.ok) throw new Error(result.error || "The update could not be saved."); setData(result); setStatus(success); } catch (error) { setStatus(error instanceof Error ? error.message : "The update could not be saved."); } finally { setBusy(""); } }

  const jobs = useMemo(() => data.jobs || [], [data.jobs]); const selectedJob = jobs.find((job) => job.id === selectedJobId) || null;
  const todayJobs = useMemo(() => jobs.filter((job) => job.scheduledStart === new Date().toISOString().slice(0, 10)), [jobs]);

  return <main className="wrap trade-team-page"><SiteHeader active="direct-trade-dashboard" />
    {!authReady ? <section className="dashboard-state-card"><p>Opening the secure staff portal...</p></section> : !user ? <section className="team-auth-shell"><div className="team-auth-intro"><span>Installer team access</span><h1>Your workday, without the office clutter</h1><p>Use the email address your employer invited. Technicians see assigned jobs only. Managers and coordinators see the dispatch view their role allows.</p></div><div className="team-auth-card"><button className="customer-google-button" type="button" onClick={() => void google()} disabled={busy === "auth"}>Continue with Google</button><div className="customer-auth-tabs"><button type="button" className={mode === "signin" ? "selected" : ""} onClick={() => setMode("signin")}>Sign in</button><button type="button" className={mode === "create" ? "selected" : ""} onClick={() => setMode("create")}>Create login</button></div><form onSubmit={emailAuth}>{mode === "create" && <label><span>Your name</span><input value={name} required onChange={(event) => setName(event.target.value)} /></label>}<label><span>Invited email</span><input type="email" value={email} required onChange={(event) => setEmail(event.target.value)} /></label><label><span>Password</span><input type="password" minLength={8} required value={password} onChange={(event) => setPassword(event.target.value)} /></label><button className="btn" disabled={busy === "auth"}>{busy === "auth" ? "Please wait..." : mode === "create" ? "Create team login" : "Sign in"}</button>{mode === "signin" && <button className="customer-reset-link" type="button" onClick={() => void reset()}>Reset password</button>}</form>{status && <p role="status">{status}</p>}</div></section> : loading ? <section className="dashboard-state-card"><p>Loading assigned work...</p></section> : !data.access ? <section className="dashboard-state-card"><span>Team access required</span><h1>This login is not connected to an active installer team</h1><p>{status || "Open the invitation link from your employer, or ask them to create a fresh link."}</p><button className="btn" type="button" onClick={() => void signOut(firebaseAuth)}>Use another account</button></section> : <>
      <header className="team-portal-hero"><div><span>{data.access.role} portal</span><h1>{data.access.businessName}</h1><p>Welcome, {data.access.displayName}. {data.access.role === "technician" ? "Only work assigned to you is visible." : "Coordinate the active work queue from one place."}</p></div><div><strong>{todayJobs.length}</strong><span>jobs today</span><button type="button" onClick={() => void signOut(firebaseAuth)}>Sign out</button></div></header>
      <section className="team-queue-summary"><article><span>Assigned work</span><strong>{jobs.filter((job) => !["completed", "cancelled"].includes(job.stage)).length}</strong></article><article><span>Today</span><strong>{todayJobs.length}</strong></article><article><span>Waiting</span><strong>{jobs.filter((job) => job.stage === "blocked").length}</strong></article><article><span>Open tasks</span><strong>{jobs.flatMap((job) => job.tasks).filter((task) => task.status !== "done").length}</strong></article></section>
      <div className="team-queue-layout"><aside className="team-job-queue"><header><strong>Work queue</strong><span>{jobs.length} visible</span></header>{jobs.length ? jobs.map((job) => <button type="button" key={job.id} className={selectedJobId === job.id ? "active" : ""} onClick={() => setSelectedJobId(job.id)}><span>{job.workNumber}<b>{job.priority}</b></span><strong>{job.title}</strong><small>{job.scheduledStart || "Not scheduled"} | {job.assigneeLabel || "Unassigned"}</small></button>) : <div className="crm-empty"><strong>No work assigned</strong><span>Your dispatcher can assign the next job.</span></div>}</aside><section className="team-job-focus">{selectedJob ? <article><header><div><span>{selectedJob.workNumber}</span><h2>{selectedJob.title}</h2><p>{selectedJob.protectedJob ? `${selectedJob.siteArea || "Service region"}. AEA protected job, no customer identity or street address.` : selectedJob.serviceAddress || "Direct customer address has not been added."}</p></div><label><span>Job stage</span><select value={selectedJob.stage} disabled={busy === `job:${selectedJob.id}`} onChange={(event) => void update({ action: "update_job", workOrderId: selectedJob.id, stage: event.target.value }, `job:${selectedJob.id}`, "Job stage updated.")}>{stages.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></header>{data.access.canDispatch && <label className="team-portal-assignment"><span>Assigned technician</span><select value={selectedJob.assigneeMemberId} onChange={(event) => void update({ action: "assign_job", workOrderId: selectedJob.id, memberId: event.target.value }, `assign:${selectedJob.id}`, "Assignment updated.")}><option value="">Unassigned</option>{(data.members || []).filter((member) => member.status === "active").map((member) => <option key={member.id} value={member.id}>{member.displayName}</option>)}</select></label>}<section className="team-mobile-checklist"><h3>Job checklist</h3>{selectedJob.tasks.length ? selectedJob.tasks.map((task) => <label key={task.id}><input type="checkbox" checked={task.status === "done"} disabled={busy === `task:${task.id}`} onChange={(event) => void update({ action: "update_task", taskId: task.id, status: event.target.checked ? "done" : "pending" }, `task:${task.id}`, event.target.checked ? "Task completed." : "Task reopened.")} /><span>{task.title}<small>{task.dueAt ? `Due ${task.dueAt}` : "No due date"}</small></span></label>) : <div className="crm-empty"><strong>No checklist yet</strong><span>The office can add task steps from the CRM.</span></div>}</section><section className="team-field-tools"><h3>Field record</h3><TradeFieldWorkPanel user={user} workOrderId={selectedJob.id} isProtected={selectedJob.protectedJob} /></section></article> : <div className="crm-empty"><strong>Select a job</strong><span>Its work details will open here.</span></div>}</section></div>
      {status && <p className="crm-status" role="status">{status}</p>}
    </>}<SiteFooter>Team access is controlled by the installer business. AEA protected customer identity and contact details remain unavailable.</SiteFooter></main>;
}
