import Link from "next/link";
import { SiteFooter, SiteHeader } from "@/components/ComparatorChrome";
import { JsonLd } from "@/components/JsonLd";
import { buildPlatformMetadata, PUBLIC_SITE } from "@/lib/public-site";

export const metadata = buildPlatformMetadata({
  path: "/platform",
  title: "How AEA Helps: Compare Bills and Plan Home Energy Upgrades",
  description: "Understand your bills, compare solar and electrification, choose the right assessment and prepare better quotes. See what is free and when expert help matters.",
});

const steps = [
  { title: "Understand the starting point", label: "Your home and bills", items: ["Start with a recent bill and your postcode", "Use smart-meter readings for a clearer picture of when you use electricity", "Note which rooms feel uncomfortable and which appliances need replacing"], href: "/guides", action: "Choose a guide" },
  { title: "Compare the options", label: "Plan costs and upgrades", items: ["Compare published electricity or mains gas offers", "Explore solar alone against solar with a battery", "Estimate running-cost changes when replacing gas appliances"], href: "/case-studies", action: "See the savings examples" },
  { title: "Put the work in order", label: "Now, next and later", items: ["Build a home energy plan around your goal, budget and timing", "Check whether a visit or formal rating would change the decision", "Confirm rebates for the exact work before counting a discount"], href: "/plan", action: "Build my home energy plan" },
  { title: "Get a useful written quote", label: "When you are ready", items: ["Specify the equipment, installation and enabling work", "Check credentials, site suitability, exclusions and support", "Choose to send an enquiry, then decide who to work with"], href: "/guides/project-preparation", action: "Prepare for quotes" },
] as const;

export default function PlatformPage() {
  return <main className="wrap platform-page">
    <SiteHeader active="guides" />
    <JsonLd data={{ "@context": "https://schema.org", "@type": "WebPage", "@id": `${PUBLIC_SITE.apexUrl}/platform#webpage`, url: `${PUBLIC_SITE.apexUrl}/platform`, name: "How Australian Energy Assessments helps households", description: metadata.description, dateModified: "2026-10-09", inLanguage: "en-AU", isPartOf: { "@id": PUBLIC_SITE.apexWebsiteId }, publisher: { "@id": PUBLIC_SITE.organizationId } }} />
    <header className="platform-hero"><div><span>From a question to a clearer decision</span><h1>Understand your options before you spend</h1><p>Energy plans, ratings, rebates and upgrade quotes can be difficult to connect. Australian Energy Assessments brings the explanations, comparison tools and assessment pathways together so you can work out what your home needs and what to confirm next.</p><div><Link className="btn" href="/plan">Build my home energy plan</Link><Link className="btn ghost" href="/guides">Start with a guide</Link></div></div><aside><strong>You can start without an account</strong><ol><li>Read a plain-language guide</li><li>Try a comparison with your bill</li><li>Save a practical home energy plan</li><li>Ask for help when you choose</li></ol><p>Reading and using the tools does not send an enquiry. Review the named recipients and information before submitting a request.</p></aside></header>

    <section className="platform-workspaces" aria-labelledby="platform-steps"><div className="guide-section-heading"><span>One decision at a time</span><h2 id="platform-steps">A practical path through your home energy choices</h2><p>Start at the stage that fits you. You do not need to replace everything or complete every tool.</p></div><div>{steps.map((step, index) => <article key={step.title}><span>Step {index + 1}</span><small>{step.label}</small><h3>{step.title}</h3><ul>{step.items.map((item) => <li key={item}>{item}</li>)}</ul><Link className="platform-access-link" href={step.href}>{step.action}</Link></article>)}</div></section>

    <section className="platform-access" aria-labelledby="platform-free"><div className="guide-section-heading"><span>Know what you are getting</span><h2 id="platform-free">Free tools help you prepare. Assessments provide property-specific evidence.</h2><p>The guides, comparisons, home energy planner and Wattzun guidance are free. Property visits, formal ratings and installation work have their own scope and prices.</p></div><div className="guide-principle-grid"><article><strong>Compare and plan</strong><p>Use your bills and household answers to explore options. These tools estimate costs and priorities; they do not inspect the home or issue a rating certificate.</p><Link href="/compare">Compare electricity</Link> · <Link href="/gas-compare">Compare gas</Link></article><article><strong>Practical on-site advice</strong><p>A visit can help investigate comfort problems and identify an order of improvements. This advice service includes a written summary without a formal rating certificate.</p><Link href="/services/onsite-energy-assessment">See the advice service and price</Link></article><article><strong>Formal ratings and approvals</strong><p>An existing-home rating and a plan-based new-home NatHERS assessment use different methods and outputs. Choose the pathway for your property and the decision it must support.</p><Link href="/assessments">Choose the right assessment</Link></article></div></section>

    <section className="platform-difference"><div><span>Useful evidence, clear limits</span><h2>How to use a result well</h2></div><div><article><strong>Your bill matters</strong><p>Plan costs depend on usage, timing, network and eligibility. A published plan ID can help identify an offer, but its rates still need checking against your current bill.</p></article><article><strong>Your roof matters</strong><p>A postcode-based solar estimate reflects local climate. Shade, roof layout, installation and export limits need site-specific checks.</p></article><article><strong>Your quote matters</strong><p>Planning prices are starting points. Enter the complete installed price after confirmed discounts and compare the same equipment and work.</p></article><article><strong>Your choice matters</strong><p>We do not sell household leads or offer paid placement. You decide whether to share an enquiry and whether to accept any quote.</p></article></div></section>

    <section className="guide-callout"><div><h2>See how the numbers change a decision</h2><p>Follow four worked examples of plan timing, using solar at home, adding storage and ending a gas connection. Each shows its assumed figures and the next question to ask.</p></div><Link href="/case-studies">Explore energy savings examples</Link></section>
    <section className="guide-callout"><div><h2>Prefer to talk it through?</h2><p>A five-minute call helps confirm the right assessment and booking logistics. It is separate from a paid assessment or installation quote.</p></div><Link href="/book-an-assessment">Book a quick call</Link></section>
    <section className="guide-section"><div className="guide-section-heading"><span>For businesses and community teams</span><h2>Explore TLink for your work</h2></div><p>See how the trade workspace supports service businesses, and how the council workspace connects community programs with maps and reporting.</p><div className="guide-source-links"><Link href="/direct-trade/for-trades">TLink for trades and businesses</Link><Link href="/direct-trade/for-councils">TLink for councils</Link><Link href="/direct-trade/standards">Read the participation standards</Link></div></section>
    <SiteFooter>Estimates support decisions and remain indicative. Confirm current rates, eligibility, licences, site suitability and the full written quote before committing.</SiteFooter>
  </main>;
}
