import Link from "next/link";
import { SiteFooter, SiteHeader } from "@/components/ComparatorChrome";
import { JsonLd } from "@/components/JsonLd";
import { buildPlatformMetadata, PUBLIC_SITE } from "@/lib/public-site";
import { CALENDLY_BOOKING_URL } from "@/lib/assessment-booking";
import styles from "./page.module.css";

export const metadata = buildPlatformMetadata({
  path: "/direct-trade/for-councils",
  title: "TLink for Councils | Community Energy Programs, Maps and Reporting",
  description: "Give community energy programs a clearer path from outreach to upgrades. Explore TLink council campaign pages, postcode maps, local business participation and reporting.",
});

const benefits = [
  { number: "01", title: "Give your community a clear next step", text: "Connect outreach to a branded upgrade page, practical household guidance and an enquiry pathway. Give residents somewhere useful to go after a campaign or information session." },
  { number: "02", title: "See your area, not another spreadsheet", text: "Explore postcode maps with TLink activity, published solar and battery installation data, Victorian upgrade activity and Census context. Select a layer and look more closely at a postcode." },
  { number: "03", title: "Bring local businesses into the picture", text: "Understand the approved businesses participating in your area and the services they offer. View local participation alongside recorded upgrades and work value." },
  { number: "04", title: "Follow the journey after outreach", text: "Use campaign and information-session referral links to follow attributed enquiries and completed TLink work. Enquiry-to-quote reporting adds another view of the customer journey." },
  { number: "05", title: "Make reporting easier to share", text: "Export summaries and published community data in CSV or PDF for briefings and program reviews. Prepare monthly reports, with scheduled email where delivery has been configured." },
  { number: "06", title: "Give the team the right access", text: "Work in an approved council scope with owner, editor and viewer roles. Keep campaign management, settings and reporting access appropriate to each colleague." },
] as const;

export default function TLinkForCouncilsPage() {
  return <main className={`wrap ${styles.page}`}>
    <SiteHeader active="direct-trade-access" />
    <JsonLd data={{ "@context": "https://schema.org", "@type": "WebPage", url: `${PUBLIC_SITE.apexUrl}/direct-trade/for-councils`, name: "TLink for councils", description: metadata.description, dateModified: "2026-10-09", inLanguage: "en-AU", publisher: { "@id": PUBLIC_SITE.organizationId }, isPartOf: { "@id": PUBLIC_SITE.apexWebsiteId } }} />
    <header className={styles.hero}>
      <div className={styles.heroCopy}><span className={styles.brand}><img src="/tlink-icon-192.png" alt="" width={40} height={40} />TLink for councils</span><h1>Turn local ambition into <span>a clearer path to action.</span></h1><p>Give residents somewhere to start. Connect local businesses to the work. See community energy programs through maps, campaign journeys and reporting in one council workspace.</p><div className={styles.actions}><a className={styles.primary} href={CALENDLY_BOOKING_URL}>Book a council walkthrough <span aria-hidden="true">↗</span></a><Link className={styles.secondary} href="/council/demo">Explore the demonstration</Link></div><p className={styles.heroNote}>For sustainability, community engagement and economic development teams.</p></div>
      <figure className={styles.heroVisual}><img src="/tlink-council-demo-dashboard.jpg" alt="TLink council demonstration dashboard with separately labelled public community data and fictional platform activity" width={1920} height={1440} fetchPriority="high" /><figcaption>Actual TLink demonstration. Official public community data and fictional TLink participation are labelled separately. Certificate estimates are not measured annual savings or council-attributed outcomes. No customer records are shown.</figcaption></figure>
    </header>
    <nav className={styles.quickLinks} aria-label="TLink council page topics"><a href="#council-benefits">Why TLink</a><a href="#council-map">Maps and local context</a><a href="#council-journey">Campaign journey</a><a href="#council-reporting">What the numbers mean</a></nav>

    <section className={styles.section} id="council-benefits" aria-labelledby="council-benefits-title"><div className={styles.heading}><span>Engagement, delivery and evidence</span><h2 id="council-benefits-title">A useful next step for residents.<br />A clearer view for your team.</h2><p>TLink connects the public-facing journey with a council workspace, so the program has somewhere to begin and the team has a practical way to follow it.</p></div><div className={styles.benefits}>{benefits.map((benefit) => <article key={benefit.number}><span>{benefit.number}</span><h3>{benefit.title}</h3><p>{benefit.text}</p></article>)}</div></section>

    <section className={styles.mapSection} id="council-map" aria-labelledby="council-map-title"><div><span className={styles.eyebrow}>Put the area in context</span><h2 id="council-map-title">From a region-wide view to a postcode-level question.</h2><p>Look at the patterns that can inform your next conversation: where upgrades are recorded, what the published community data covers and which businesses participate.</p><ul><li>Switch between TLink, Clean Energy Regulator, Victorian Energy Upgrades and Census layers.</li><li>Inspect postcode totals with their source dates and coverage.</li><li>Explore approved local business participation within your council scope.</li></ul><Link className={styles.textLink} href="/council/demo?workspace=map">Try the demonstration map <span aria-hidden="true">↗</span></Link></div><figure><img src="/tlink-council-demo-map.jpg" alt="TLink demonstration map showing public Victorian upgrade activity across seven postcode areas and fictional business profiles" width={1920} height={1440} loading="lazy" /><figcaption>Actual demonstration map with official public upgrade activity and fictional business profiles. ABS Postal Areas approximate postcodes, not council boundaries or customer locations. The example area and branding do not imply council affiliation or endorsement.</figcaption></figure></section>

    <section className={styles.section} id="council-journey" aria-labelledby="council-journey-title"><div className={styles.heading}><span>More than a campaign link</span><h2 id="council-journey-title">Give the message somewhere useful to land.</h2><p>A practical campaign journey helps people move from interest to an informed request. Your council team can then follow the activity attributed to that pathway.</p></div><ol className={styles.journey}><li><span>01</span><h3>Reach the community</h3><p>Use your existing newsletters, events and outreach with a dedicated campaign or session referral link.</p></li><li><span>02</span><h3>Help people understand</h3><p>Send residents to a branded program page with household and business upgrade pathways.</p></li><li><span>03</span><h3>Connect a chosen enquiry</h3><p>People review the information they share and choose whether to ask suitable businesses for help.</p></li><li><span>04</span><h3>Follow recorded progress</h3><p>Follow campaign-attributed enquiries and completed work, alongside separate enquiry-to-quote counters for your council customer page.</p></li></ol><div className={styles.note}><strong>Your outreach stays yours.</strong><p>TLink supports the referral and upgrade journey. Your existing channels manage invitations, attendance and meetings; an enquiry count is not an attendance count.</p></div></section>

    <section className={styles.reporting} id="council-reporting" aria-labelledby="council-reporting-title"><div className={styles.heading}><span>Credible reporting starts with clear definitions</span><h2 id="council-reporting-title">Know what the numbers show.</h2></div><div className={styles.reportingGrid}><article><h3>Three views, kept distinct</h3><p>TLink shows recorded platform activity. Clean Energy Regulator and Victorian Energy Upgrades data provide published area context. These sources have different coverage and are not added together as one program total.</p></article><article><h3>Source dates and missing coverage</h3><p>Published data can lag and some measures may be unavailable for an area. The workspace shows source dates, coverage and missing values rather than turning missing data into zero.</p></article><article><h3>Area patterns, not household surveillance</h3><p>Reporting is aggregated and small cohorts are withheld. Census context is from 2021 Postal Areas; postcode geography is not an exact council boundary or a profile of an individual resident.</p></article><article><h3>Activity is not automatically impact</h3><p>Attributed work does not prove the campaign caused it. Work value is not council revenue, business participation is not jobs created, and deemed certificate estimates are not measured current-year emissions reductions.</p></article></div></section>

    <section className={styles.finalCta}><span className={styles.eyebrow}>Start with a walkthrough</span><h2>See how TLink could fit your community program.</h2><p>Bring your area, program goals and reporting questions. We can walk through the demonstration and discuss the workspace scope and access your team would need.</p><div className={styles.actions}><a className={styles.primary} href={CALENDLY_BOOKING_URL}>Book a council walkthrough <span aria-hidden="true">↗</span></a><Link className={styles.secondary} href="/council/demo">Explore the demonstration</Link></div><p className={styles.accessNote}>Already invited? <Link href="/council">Sign in to your council workspace</Link>. Live workspace access requires approved membership; creating an account alone does not grant access.</p></section>
    <div className={styles.related}><Link href="/direct-trade/for-trades">TLink for trades and service businesses</Link><Link href="/platform">How AEA helps households</Link></div>
    <SiteFooter>Demonstration TLink records are fictional. Public data retains its source dates and geographic limits. Reporting and access depend on the approved council scope and available evidence.</SiteFooter>
  </main>;
}
